### ISSUE TITLE
[1.18.2] Gem weights are broken

### ISSUE THREAD

**Issue by Auuki** [Shadows-of-Fire/Apotheosis#1004]
**MC 1.18.2, newest Apotheosis version**
**1. When I set weights of gems to 0 apart from mythic at 8000, I can't create a world.**

`Description: Feature placement

java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:143) ~[?:?] {re:mixin}
	at shadows.apotheosis.adventure.loot.LootRarity.random(LootRarity.java:204) ~[Apotheosis-1.18.2-5.8.1.jar%2359!/:5.8.1] {re:classloading}
	at shadows.apotheosis.adventure.loot.LootRarity.random(LootRarity.java:199) ~[Apotheosis-1.18.2-5.8.1.jar%2359!/:5.8.1] {re:classloading}
	at shadows.apotheosis.adventure.loot.AffixConvertLootModifier.doApply(AffixConvertLootModifier.java:36) ~[Apotheosis-1.18.2-5.8.1.jar%2359!/:5.8.1] {re:classloading}
	at net.minecraftforge.common.loot.LootModifier.apply(LootModifier.java:39) ~[forge-1.18.2-40.2.10-universal.jar%23201!/:?] {re:classloading}
	at net.minecraftforge.common.ForgeHooks.modifyLoot(ForgeHooks.java:1306) ~[forge-1.18.2-40.2.10-universal.jar%23201!/:?] {re:classloading}
	at net.minecraft.world.level.storage.loot.LootTable.m_79129_(LootTable.java:89) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:balm.mixins.json:LootTableMixin,pl:mixin:APP:botania_xplat.mixins.json:MixinLootTable,pl:mixin:APP:quark.mixins.json:accessor.AccessorLootTable,pl:mixin:APP:puzzleslib.forge.mixins.json:accessor.LootTableForgeAccessor,pl:mixin:A}
	at tallestegg.guardvillagers.entities.Guard.getItemsFromLootTable(Guard.java:618) ~[guardvillagers-1.18.2.1.4.3.jar%23121!/:1.18.2.1.4.3] {re:classloading}
	at tallestegg.guardvillagers.entities.Guard.m_6851_(Guard.java:605) ~[guardvillagers-1.18.2.1.4.3.jar%23121!/:1.18.2.1.4.3] {re:classloading}
	at tallestegg.guardvillagers.entities.Guard.m_6518_(Guard.java:208) ~[guardvillagers-1.18.2.1.4.3.jar%23121!/:1.18.2.1.4.3] {re:classloading}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.lambda$addEntitiesToWorld$5(StructureTemplate.java:423) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:feature_nbt_deadlock_be_gone.mixins.json:StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.TemplateAccessor,pl:mixin:APP:blueprint.mixins.json:StructureTemplateMixin,pl:mixin:APP:quark.mixins.json:StructureTemplateMixin,pl:mixin:A}
	at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.addEntitiesToWorld(StructureTemplate.java:418) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:feature_nbt_deadlock_be_gone.mixins.json:StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.TemplateAccessor,pl:mixin:APP:blueprint.mixins.json:StructureTemplateMixin,pl:mixin:APP:quark.mixins.json:StructureTemplateMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.templatesystem.StructureTemplate.m_74536_(StructureTemplate.java:336) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:feature_nbt_deadlock_be_gone.mixins.json:StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.StructureTemplateMixin,pl:mixin:APP:integrated_api.mixins.json:structures.TemplateAccessor,pl:mixin:APP:blueprint.mixins.json:StructureTemplateMixin,pl:mixin:APP:quark.mixins.json:StructureTemplateMixin,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.pools.SinglePoolElement.m_207251_(SinglePoolElement.java:126) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:integrated_api.mixins.json:structures.SinglePoolElementAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_192416_(PoolElementStructurePiece.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:integrated_api.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.PoolElementStructurePiece.m_183269_(PoolElementStructurePiece.java:84) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,re:classloading,pl:mixin:APP:integrated_api.mixins.json:structures.PoolElementStructurePieceAccessor,pl:mixin:A}
	at net.minecraft.world.level.levelgen.structure.StructureStart.m_7129_(StructureStart.java:53) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:blueprint.mixins.json:StructureStartMixin,pl:mixin:APP:quark.mixins.json:StructureStartMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_211641_(ChunkGenerator.java:438) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:A}
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:422) ~[guava-31.0.1-jre.jar%2330!/:?] {re:mixin}
	at net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:437) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:ChunkGeneratorMixin,pl:mixin:APP:modernfix-common.mixins.json:perf.cache_strongholds.ChunkGeneratorMixin,pl:mixin:A}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:flytre_lib.mixins.json:base.ThreadedAnvilChunkStorageAccessor,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38) ~[datafixerupper-4.1.27.jar%2335!/:?] {}
	at net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$24(ChunkMap.java:587) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:modernfix-common.mixins.json:bugfix.paper_chunk_patches.ChunkMapMixin,pl:mixin:APP:modernfix-forge.mixins.json:bugfix.chunk_deadlock.ChunkMapLoadMixin,pl:mixin:APP:flytre_lib.mixins.json:base.ThreadedAnvilChunkStorageAccessor,pl:mixin:APP:smoothchunk.mixins.json:ChunkMapMixin,pl:mixin:A}
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?] {}
	at net.minecraft.server.level.ChunkTaskPriorityQueueSorter.m_143188_(ChunkTaskPriorityQueueSorter.java:62) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18759_(ProcessorMailbox.java:91) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.m_18747_(ProcessorMailbox.java:146) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:classloading}
	at net.minecraft.util.thread.ProcessorMailbox.run(ProcessorMailbox.java:102) ~[client-1.18.2-20220404.173914-srg.jar%23196!/:?] {re:classloading}
	at java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:mixin,re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {re:mixin}`

**2. When I set weights of gems to 1 apart from mythic at 8000 and gem spawn rate in chests to 1.0, I barely get any gems and in fact the first one I got after like 20 chests was rare.**

**Comment by Shadows-of-Fire** [comment]
It is not possible to manipulate the rarities in the way you described, at least not in 1.18.
And 1.18 is not supported.
