### ISSUE TITLE
apotheosis compat with lootbeams cause crash. 1.20.1 forge.

### ISSUE THREAD

**Issue by TheRanker** [Shadows-of-Fire/Apotheosis#1083]
seems after latest update on the forge 1.20.1 .. apotheosis compat for lootbeams is broken?

[18Nov2023 20:33:47.700] [Render thread/ERROR] [net.minecraft.client.Minecraft/FATAL]: Reported exception thrown!
net.minecraft.ReportedException: Ticking entity
	at net.minecraft.world.level.Level.m_46653_(Level.java:488) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_194182_(ClientLevel.java:256) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.world.level.entity.EntityTickList.m_156910_(EntityTickList.java:54) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104804_(ClientLevel.java:254) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.Minecraft.m_91398_(Minecraft.java:1814) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1112) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:718) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.main.Main.main(Main.java:218) ~[forge-47.2.4.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.runTarget(CommonLaunchHandler.java:111) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonLaunchHandler.clientService(CommonLaunchHandler.java:99) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$makeService$0(CommonClientLaunchHandler.java:25) ~[fmlloader-1.20.1-47.2.4.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:108) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:78) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) ~[modlauncher-10.0.9.jar:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) ~[bootstraplauncher-1.1.2.jar:?]
Caused by: java.lang.NoSuchMethodError: 'dev.shadowsoffire.placebo.reload.TypeKeyed dev.shadowsoffire.placebo.reload.DynamicHolder.get()'
	at com.lootbeams.compat.ApotheosisCompat.getRarityName(ApotheosisCompat.java:17) ~[lootbeams-1.20.1-1.2.2.jar%23537!/:1.20.1-1.2.2]
	at com.lootbeams.LootBeamRenderer.compatRarityCheck(LootBeamRenderer.java:174) ~[lootbeams-1.20.1-1.2.2.jar%23537!/:1.20.1-1.2.2]
	at com.lootbeams.ClientSetup.playDropSound(ClientSetup.java:237) ~[lootbeams-1.20.1-1.2.2.jar%23537!/:1.20.1-1.2.2]
	at net.minecraft.world.entity.item.ItemEntity.handler$zhb000$onTick(ItemEntity.java:1032) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.world.entity.item.ItemEntity.m_8119_(ItemEntity.java:186) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.client.multiplayer.ClientLevel.m_104639_(ClientLevel.java:274) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	at net.minecraft.world.level.Level.m_46653_(Level.java:479) ~[client-1.20.1-20230612.114412-srg.jar%23648!/:?]
	... 22 more

**Comment by Shadows-of-Fire** [comment]
Loot beams is outdated, report it to them.
