### ISSUE TITLE
LootRule. And other errors Apotheosis. Forge 1.19.2

### ISSUE THREAD

**Issue by Krimatoria** [Shadows-of-Fire/Apotheosis#1154]
**These are all errors from the three mods. Do I need to do something about it? Or it doesn't affect the game. I have attached a list of Apotheosis mods.**

ApothicCurios-1.19.2-1.0.3.jar
apotheotic_additions1.0.2_v1.19.2.jar
Apotheosis-1.19.2-6.4.1.jar

[Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.
[Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.
[Render thread/ERROR] [Apotheosis : Adventure/]: Use of the "rarity" key in affix loot pool entries is deprecated and will be removed in a future release.

[Render thread/ERROR] [Apotheosis : Adventure/]: Failed parsing affix_loot_entries file apotheotic_additions:overworld/soul_stained_steel_scythe.
[Render thread/ERROR] [Apotheosis : Adventure/]: Underlying Exception: 
java.lang.RuntimeException: Unknown registry key in ResourceKey[minecraft:root / minecraft:item]: malum:soul_stained_steel_scythe
	at com.mojang.serialization.DataResult.lambda$getOrThrow$4(DataResult.java:100) ~[datafixerupper-5.0.28.jar%2393!/:?]
	at com.mojang.datafixers.util.Either$Right.map(Either.java:99) ~[datafixerupper-5.0.28.jar%2393!/:?]
	at com.mojang.serialization.DataResult.getOrThrow(DataResult.java:93) ~[datafixerupper-5.0.28.jar%2393!/:?]
	at shadows.placebo.json.PSerializer.lambda$fromCodec$2(PSerializer.java:122) ~[Placebo-1.19.2-7.3.5.jar%23582!/:7.3.5]
	at shadows.placebo.json.PSerializer.read(PSerializer.java:76) ~[Placebo-1.19.2-7.3.5.jar%23582!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:99) ~[Placebo-1.19.2-7.3.5.jar%23582!/:7.3.5]
	at java.util.HashMap.forEach(Unknown Source) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:91) ~[Placebo-1.19.2-7.3.5.jar%23582!/:7.3.5]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:47) ~[Placebo-1.19.2-7.3.5.jar%23582!/:7.3.5]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(Unknown Source) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(Unknown Source) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.Minecraft.m_18701_(Minecraft.java:5919) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233096_(WorldOpenFlows.java:130) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233122_(WorldOpenFlows.java:109) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldOpenFlows.m_233119_(WorldOpenFlows.java:124) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.screens.worldselection.WorldSelectionList$WorldListEntry.m_101743_(WorldSelectionList.java:531) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at java.util.Optional.ifPresent(Unknown Source) ~[?:?]
	at net.minecraft.client.gui.screens.worldselection.SelectWorldScreen.m_101375_(SelectWorldScreen.java:75) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:43) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:110) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:522) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:103) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallback$Container.invoke(GLFWMouseButtonCallback.java:81) ~[lwjgl-glfw-3.3.1.jar%2362!/:build 7]
	at bre2el.fpsreducer.handler.glfw.InputEventHandler$MouseButtonEventHandler.invoke(InputEventHandler.java:133) ~[FpsReducer2-forge-1.19.2-2.1.jar%23503!/:1.19.2-2.1]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:43) ~[lwjgl-glfw-3.3.1.jar%2362!/:build 7]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.3.1.jar%2368!/:build 7]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3403) ~[lwjgl-glfw-3.3.1.jar%2362!/:build 7]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:204) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:337) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1143) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23663!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.3.5.jar%23122!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%23109!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67) [ForgeWrapper-mmc4.jar:mmc4]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]

[Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category helmetRequired: 3; Provided: 2
[Render thread/ERROR] [Apotheosis : Adventure/]: Insufficient number of affixes to satisfy the loot rules (ignoring backup rules) of rarity mythic for category bootsRequired: 3; Provided: 2
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/common/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/common/STAT/1.0!
[Render thread/ERROR] [com.mojang.blaze3d.audio.OpenAlUtil/]: Deleting stream buffers: Invalid operation.
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/0.45!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/uncommon/STAT/0.45!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to execute LootRule minecraft:air/common/STAT/1.0!
[Server thread/ERROR] [Apotheosis : Adventure/]: Failed to locate any gear sets matching the following predicates: 
[Server thread/ERROR] [Apotheosis : Adventure/]: SetPredicate[#terrible]

**Comment by SiverDX** [comment]
See https://github.com/Shadows-of-Fire/Apotheosis/issues/1152

**Comment by Krimatoria** [comment]
> См. [№ 1152.](https://github.com/Shadows-of-Fire/Apotheosis/issues/1152)

I saw. But I don't understand what that means. Can you explain? "This is an invalid file from the apophatic add-ons." What does an invalid file mean?

**Comment by SiverDX** [comment]
https://www.curseforge.com/minecraft/mc-mods/apotheotic-additions is shipping invalid content
ask them about it
