### ISSUE TITLE
[BUG] Error when i try to open enchanting table

### ISSUE THREAD

**Issue by vSKAH** [Shadows-of-Fire/Apotheosis#1256]
Gameversion: 1.20.1
Forge: 47.2.30
Apotheosis-1.20.1-7.3.4
ApothicAttributes-1.20.1-1.3.4
Placebo-1.20.1-8.6.1
Patchouli-1.20.1-84-FORGE

```
[12:33:49] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@59604507, suppressing error
java.lang.NullPointerException: Cannot read field "f_8906_" because the return value of "java.util.function.Supplier.get()" is null
        at net.minecraftforge.network.PacketDistributor.lambda$playerConsumer$1(PacketDistributor.java:203) ~[forge-1.20.1-47.2.30-universal.jar%23594!/:?] {re:classloading,re:mixin}
        at net.minecraftforge.network.PacketDistributor$PacketTarget.send(PacketDistributor.java:165) ~[forge-1.20.1-47.2.30-universal.jar%23594!/:?] {re:mixin,re:classloading}
        at net.minecraftforge.network.simple.SimpleChannel.send(SimpleChannel.java:107) ~[forge-1.20.1-47.2.30-universal.jar%23594!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectivity.mixins.json:SimpleChannelMixin,pl:mixin:A}
        at dev.shadowsoffire.placebo.network.PacketDistro.sendTo(PacketDistro.java:27) ~[Placebo-1.20.1-8.6.1.jar%23514!/:8.6.1] {re:classloading}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantmentMenu.lambda$gatherStats$3(ApothEnchantmentMenu.java:244) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading}
        at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantmentMenu.gatherStats(ApothEnchantmentMenu.java:242) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantmentMenu.lambda$slotsChanged$1(ApothEnchantmentMenu.java:177) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading}
        at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantmentMenu.m_6199_(ApothEnchantmentMenu.java:174) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading}
        at net.minecraft.world.inventory.EnchantmentMenu$1.m_6596_(EnchantmentMenu.java:30) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainer.java:144) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:63) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:SlotAccessor,pl:mixin:APP:allurement.mixins.json:SlotMixin,pl:mixin:A}
        at net.minecraft.world.inventory.EnchantmentMenu.handler$zje000$open(EnchantmentMenu.java:526) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lapisreserve.mixins.json:EnchantScreen,pl:mixin:APP:mixins.deeperdarker.json:ContainerMenuMixin,pl:mixin:A}
        at net.minecraft.world.inventory.EnchantmentMenu.<init>(EnchantmentMenu.java:82) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:lapisreserve.mixins.json:EnchantScreen,pl:mixin:APP:mixins.deeperdarker.json:ContainerMenuMixin,pl:mixin:A}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantmentMenu.<init>(ApothEnchantmentMenu.java:79) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading}
        at dev.shadowsoffire.apotheosis.ench.table.ApothEnchantBlock.lambda$getMenuProvider$1(ApothEnchantBlock.java:38) ~[Apotheosis-1.20.1-7.3.4.jar%23358!/:7.3.4] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.server.level.ServerPlayer.m_5893_(ServerPlayer.java:963) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_serverplayer,xf:fml:xaeroworldmap:xaero_wm_serverplayer,pl:mixin:APP:betterendisland.mixins.json:ServerPlayerMixin,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:lapisreserve.mixins.json:ServerPlayerReserve,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:krypton.mixins.json:shared.player.ServerPlayerEntityMixin,pl:mixin:APP:deep_aether.mixins.json:ServerPlayerMixin,pl:mixin:APP:dusk.mixins.json:ServerPlayerSleepMixin,pl:mixin:APP:craterlib.mixins.json:events.ServerPlayerMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:chunksending.mixins.json:ServerPlayerChunkSending,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:railways-common.mixins.json:conductor_possession.ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.world.level.block.EnchantmentTableBlock.m_6227_(EnchantmentTableBlock.java:83) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:allurement.mixins.json:EnchantmentTableBlockMixin,pl:mixin:A}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(MixinBlockStateBase.java:778) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:snowrealmagic.mixins.json:BlockStateMixin,pl:mixin:APP:framedblocks.mixin.json:MixinBlockStateBase,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:ars_nouveau.mixins.json:redstone.RedstoneLevelMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:mixins.integrateddynamics.json:MixinBlockStateBase,pl:mixin:APP:canary.mixins.json:ai.pathing.BlockStateBaseMixin,pl:mixin:APP:galosphere.mixins.json:BlockStateBaseMixin,pl:mixin:APP:twigs.mixins.json:BlockStateBaseMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:expandability-common.mixins.json:fluidcollision.BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:343) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1057) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:supplementaries-common.mixins.json:ServerGamePacketListenerMixin,pl:mixin:APP:krypton.mixins.json:shared.network.util.ServerPlayNetworkHandlerAccessor,pl:mixin:APP:craterlib.mixins.json:events.ServerGamePacketListenerImplMixin,pl:mixin:APP:immersiveengineering.mixins.json:accessors.ServerPlayNetHandlerAccess,pl:mixin:APP:ad_astra-common.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:tetra.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:APP:aether.mixins.json:common.accessor.ServerGamePacketListenerImplAccessor,pl:mixin:APP:railways.mixins.json:ServerGamePacketListenerImplMixin,pl:mixin:APP:mixins.artifacts.common.json:item.umbrella.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:expandability-common.mixins.json:swimming.server.ServerGamePacketListenerImplMixin,pl:mixin:APP:connectivity.mixins.json:ServerPlayNetHandlerMixin,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_263899_(PacketUtils.java:22) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:classloading,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:156) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:770) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:161) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:130) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:753) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:747) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18699_(BlockableEventLoop.java:115) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:732) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:665) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251) ~[server-1.20.1-20230612.114412-srg.jar%23589!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,re:classloading,pl:accesstransformer:B,xf:fml:xaerominimap:xaero_minecraftserver,xf:fml:xaeroworldmap:xaero_wm_minecraftserver,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:ae2.mixins.json:spatial.MinecraftServerMixin,pl:mixin:APP:blueprint.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:840) ~[?:?] {re:mixin}
[12:34:50] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@4575f4d7, suppressing error
java.lang.NullPointerException: null
[12:34:56] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5c5eabc8, suppressing error
java.lang.NullPointerException: null
[12:35:02] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@3c312f30, suppressing error
java.lang.NullPointerException: null
[12:35:02] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@5d5d2a73, suppressing error
java.lang.NullPointerException: null
[12:35:04] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@6ef9e9b0, suppressing error
java.lang.NullPointerException: null
[12:35:04] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@ef091eb, suppressing error
java.lang.NullPointerException: null
```

**Comment by Vothm** [comment]
Hi, have you found any fix to this?

**Comment by vSKAH** [comment]
nop

**Comment by Shadows-of-Fire** [comment]
This is (iirc) caused by installing the incompatible mod Lapis Reserve, or another mod doing a similar thing.  Apoth already has this functionality.
