### ISSUE TITLE
Game Crashes almost immediately upon launching

### ISSUE THREAD

**Issue by ghost** [Shadows-of-Fire/Apotheosis#1284]
Here is the complete log when I try to launch minecraft:

MultiMC version: 0.7.0-3863

Launched instance in online mode

authserver.mojang.com resolves to:
    [N/A]

session.minecraft.net resolves to:
    [13.107.246.71]

textures.minecraft.net resolves to:
    [13.107.246.69]

api.mojang.com resolves to:
    [13.107.246.69]

Minecraft folder is:
C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/instances/1.20.1 testing ground/.minecraft

Java path is:
C:/Program Files/Java/jdk-17.0.1/bin/javaw.exe

Checking Java version...
Java is version 17.0.1, using 64-bit architecture, from Oracle Corporation.

Main Class:
  io.github.zekerzhayard.forgewrapper.installer.Main

Native path:
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/instances/1.20.1 testing ground/natives

Traits:
traits XR:Initial
traits FirstThreadOnMacOS

Libraries:
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/github/oshi/oshi-core/6.2.2/oshi-core-6.2.2.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/google/code/gson/gson/2.10/gson-2.10.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/google/guava/failureaccess/1.0.1/failureaccess-1.0.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/google/guava/guava/31.1-jre/guava-31.1-jre.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/ibm/icu/icu4j/71.1/icu4j-71.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/authlib/4.0.43/authlib-4.0.43.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/blocklist/1.0.10/blocklist-1.0.10.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/brigadier/1.1.8/brigadier-1.1.8.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/datafixerupper/6.0.8/datafixerupper-6.0.8.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/logging/1.1.1/logging-1.1.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/patchy/2.2.10/patchy-2.2.10.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/text2speech/1.17.9/text2speech-1.17.9.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/commons-codec/commons-codec/1.15/commons-codec-1.15.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/commons-io/commons-io/2.11.0/commons-io-2.11.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/commons-logging/commons-logging/1.2/commons-logging-1.2.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-buffer/4.1.82.Final/netty-buffer-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-codec/4.1.82.Final/netty-codec-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-common/4.1.82.Final/netty-common-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-handler/4.1.82.Final/netty-handler-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-resolver/4.1.82.Final/netty-resolver-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport-classes-epoll/4.1.82.Final/netty-transport-classes-epoll-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport-native-unix-common/4.1.82.Final/netty-transport-native-unix-common-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/netty/netty-transport/4.1.82.Final/netty-transport-4.1.82.Final.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/it/unimi/dsi/fastutil/8.5.9/fastutil-8.5.9.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/java/dev/jna/jna-platform/5.12.1/jna-platform-5.12.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/java/dev/jna/jna/5.12.1/jna-5.12.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/sf/jopt-simple/jopt-simple/5.0.4/jopt-simple-5.0.4.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-compress/1.21/commons-compress-1.21.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/commons/commons-lang3/3.12.0/commons-lang3-3.12.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpclient/4.5.13/httpclient-4.5.13.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/httpcomponents/httpcore/4.4.15/httpcore-4.4.15.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-api/2.19.0/log4j-api-2.19.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-core/2.19.0/log4j-core-2.19.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/logging/log4j/log4j-slf4j2-impl/2.19.0/log4j-slf4j2-impl-2.19.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/joml/joml/1.10.5/joml-1.10.5.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/slf4j/slf4j-api/2.0.1/slf4j-api-2.0.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/io/github/zekerzhayard/ForgeWrapper/mmc5/ForgeWrapper-mmc5.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/cpw/mods/securejarhandler/2.1.10/securejarhandler-2.1.10.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm/9.7/asm-9.7.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-commons/9.7/asm-commons-9.7.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-tree/9.7/asm-tree-9.7.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-util/9.7/asm-util-9.7.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/ow2/asm/asm-analysis/9.7/asm-analysis-9.7.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/accesstransformers/8.0.4/accesstransformers-8.0.4.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/antlr/antlr4-runtime/4.9.1/antlr4-runtime-4.9.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/eventbus/6.0.5/eventbus-6.0.5.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/forgespi/7.0.1/forgespi-7.0.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/coremods/5.1.6/coremods-5.1.6.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/cpw/mods/modlauncher/10.0.9/modlauncher-10.0.9.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/unsafe/0.2.0/unsafe-0.2.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/mergetool/1.1.5/mergetool-1.1.5-api.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/electronwill/night-config/core/3.6.4/core-3.6.4.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/electronwill/night-config/toml/3.6.4/toml-3.6.4.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/apache/maven/maven-artifact/3.8.5/maven-artifact-3.8.5.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/jodah/typetools/0.6.3/typetools-0.6.3.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecrell/terminalconsoleappender/1.2.0/terminalconsoleappender-1.2.0.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/jline/jline-reader/3.12.1/jline-reader-3.12.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/jline/jline-terminal/3.12.1/jline-terminal-3.12.1.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/openjdk/nashorn/nashorn-core/15.3/nashorn-core-15.3.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarSelector/0.3.19/JarJarSelector-0.3.19.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarMetadata/0.3.19/JarJarMetadata-0.3.19.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/cpw/mods/bootstraplauncher/1.1.2/bootstraplauncher-1.1.2.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/JarJarFileSystems/0.3.19/JarJarFileSystems-0.3.19.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/fmlloader/1.20.1-47.3.3/fmlloader-1.20.1-47.3.3.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/net/minecraftforge/fmlearlydisplay/1.20.1-47.3.3/fmlearlydisplay-1.20.1-47.3.3.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/com/mojang/minecraft/1.20.1/minecraft-1.20.1-client.jar

Native libraries:
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-glfw/3.3.1/lwjgl-glfw-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-jemalloc/3.3.1/lwjgl-jemalloc-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-openal/3.3.1/lwjgl-openal-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-opengl/3.3.1/lwjgl-opengl-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-stb/3.3.1/lwjgl-stb-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl-tinyfd/3.3.1/lwjgl-tinyfd-3.3.1-natives-windows.jar
  C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/libraries/org/lwjgl/lwjgl/3.3.1/lwjgl-3.3.1-natives-windows.jar

Mods:
  [✔️] Apotheosis-1.20.1-7.4.0-sources.jar
  [✔️] ApothicAttributes-1.20.1-1.3.5.jar
  [✔️] Placebo-1.20.1-8.6.2.jar

Params:
  --username Angelofdeath324 --version 1.20.1 --gameDir C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/instances/1.20.1 testing ground/.minecraft --assetsDir C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/assets --assetIndex 5 --uuid <PROFILE ID> --accessToken <ACCESS TOKEN> --userType msa --versionType release --launchTarget forgeclient --fml.forgeVersion 47.3.3 --fml.mcVersion 1.20.1 --fml.forgeGroup net.minecraftforge --fml.mcpVersion 20230612.114412

Window size: 854 x 480

Java Arguments:
[-XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump, -Xms1024m, -Xmx5120m, -Duser.language=en]

Minecraft process ID: 17612

Using onesix launcher.

Checking: MC_SLIM
Checking: MERGED_MAPPINGS
Checking: MAPPINGS
Checking: MC_EXTRA
Checking: MOJMAPS
Checking: PATCHED
Checking: MC_SRG
2024-07-01 23:41:58,182 main WARN Advanced terminal features are not available in this environment
[23:41:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher running: args [--username, Angelofdeath324, --version, 1.20.1, --gameDir, C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/instances/1.20.1 testing ground/.minecraft, --assetsDir, C:/Users/angel/Some Random Folder/mmc-develop-win32/MultiMC/assets, --assetIndex, 5, --uuid, <PROFILE ID>, --accessToken, ????????, --userType, msa, --versionType, release, --launchTarget, forgeclient, --fml.forgeVersion, 47.3.3, --fml.mcVersion, 1.20.1, --fml.forgeGroup, net.minecraftforge, --fml.mcpVersion, 20230612.114412, --width, 854, --height, 480]
[23:41:58] [main/INFO] [cp.mo.mo.Launcher/MODLAUNCHER]: ModLauncher 10.0.9+10.0.9+main.dcd20f30 starting: java version 17.0.1 by Oracle Corporation; OS Windows 10 arch amd64 version 10.0
[23:41:58] [main/INFO] [ne.mi.fm.lo.ImmediateWindowHandler/]: Loading ImmediateWindowProvider fmlearlywindow
[23:41:58] [main/INFO] [EARLYDISPLAY/]: Trying GL version 4.6
[23:41:59] [main/INFO] [EARLYDISPLAY/]: Requested GL version 4.6 got version 4.6
[23:41:59] [main/INFO] [mixin/]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=union:/C:/Users/angel/Some%20Random%20Folder/mmc-develop-win32/MultiMC/libraries/org/spongepowered/mixin/0.8.5/mixin-0.8.5.jar%23122!/ Service=ModLauncher Env=CLIENT
[23:41:59] [pool-2-thread-1/INFO] [EARLYDISPLAY/]: GL info: NVIDIA GeForce GTX 1650/PCIe/SSE2 GL version 4.6.0 NVIDIA 545.92, NVIDIA Corporation
Failed to start Minecraft:
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at io.github.zekerzhayard.forgewrapper.installer.Main.main(Main.java:67)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)
Caused by: com.electronwill.nightconfig.core.io.ParsingException: Invalid bare key: ${modid}
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseKey(TableParser.java:175)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TableParser.parseTableName(TableParser.java:111)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:51)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.toml@3.6.4/com.electronwill.nightconfig.toml.TomlParser.parse(TomlParser.java:37)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:113)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:219)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.io.ConfigParser.parse(ConfigParser.java:202)
	at MC-BOOTSTRAP/com.electronwill.nightconfig.core@3.6.4/com.electronwill.nightconfig.core.file.WriteAsyncFileConfig.load(WriteAsyncFileConfig.java:138)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.modsTomlParser(ModFileParser.java:44)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.ModFileParser.readModList(ModFileParser.java:31)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:79)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.ModFile.<init>(ModFile.java:68)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:57)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.AbstractModProvider.createMod(AbstractModProvider.java:37)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.lambda$scanMods$0(AbstractJarFileModLocator.java:19)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at java.base/java.util.stream.SortedOps$RefSortingSink.end(SortedOps.java:395)
	at java.base/java.util.stream.Sink$ChainedReference.end(Sink.java:258)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:510)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.AbstractJarFileModLocator.scanMods(AbstractJarFileModLocator.java:19)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.moddiscovery.ModDiscoverer.discoverMods(ModDiscoverer.java:75)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.FMLLoader.beginModScan(FMLLoader.java:164)
	at MC-BOOTSTRAP/fmlloader@1.20.1-47.3.3/net.minecraftforge.fml.loading.FMLServiceProvider.beginScanning(FMLServiceProvider.java:86)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServiceDecorator.runScan(TransformationServiceDecorator.java:112)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.lambda$runScanningTransformationServices$8(TransformationServicesHandler.java:100)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1779)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:575)
	at java.base/java.util.stream.AbstractPipeline.evaluateToArrayNode(AbstractPipeline.java:260)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:616)
	at java.base/java.util.stream.ReferencePipeline.toArray(ReferencePipeline.java:622)
	at java.base/java.util.stream.ReferencePipeline.toList(ReferencePipeline.java:627)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.runScanningTransformationServices(TransformationServicesHandler.java:102)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.TransformationServicesHandler.initializeTransformationServices(TransformationServicesHandler.java:55)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.run(Launcher.java:88)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.Launcher.main(Launcher.java:78)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@10.0.9/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@1.1.2/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141)
	... 13 more
Exiting with -1
Process exited with exit code -1 (0xffffffffffffffff).
Please note that usually neither the exit code, nor its description are enough to diagnose issues!
Always upload the entire log and not just the exit code.
Clipboard copy at: 01 Jul 2024 23:51:43 -0700

**Comment by SiverDX** [comment]
`Apotheosis-1.20.1-7.4.0-sources.jar`

why did you download that
download the mod normally

![image](https://github.com/Shadows-of-Fire/Apotheosis/assets/22003703/0779bc9b-b5bf-44ae-9480-4f7b65fe4cf8)
