### ISSUE TITLE
Salvaging Table CRASHING the game

### ISSUE THREAD

**Issue by Splafty** [Shadows-of-Fire/Apotheosis#1297]
I play on the Medieval MC [FABRIC] - MMC2 modpack. 
Every time I try to use a reforging table the game crashes. I tried both on our Minecraft server and on Survival. It happens if you drag items in as well as if you shift-click.

After crashing the following text pops up:
"The game crashed whilst rendering screen
Error: java.lang.NullPointerException: Cannot invoke "net.minecraft.client.gl.ShaderProgram.addSampler(String, Object)" because "$$2" is null"
Code: -1

The detailed crash:
Time: 2024-07-15 22:37:50
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.client.gl.ShaderProgram.addSampler(String, Object)" because "$$2" is null
	at MC//net.minecraft.client.gl.VertexBuffer.drawInternal(VertexBuffer.java:130)
	at MC//net.minecraft.client.gl.VertexBuffer.draw(VertexBuffer.java:123)
	at MC//net.minecraft.client.render.BufferRenderer.drawWithGlobalProgramInternal(BufferRenderer.java:33)
	at MC//net.minecraft.client.render.BufferRenderer.drawWithGlobalProgram(BufferRenderer.java:26)
	at MC//net.minecraft.client.render.RenderLayer.draw(RenderLayer.java:865)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:97)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.method_24213(VertexConsumerProvider.java:76)
	at java.base@17.0.8/java.util.Optional.ifPresent(Optional.java:178)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:73)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.renderGuiItem(SalvagingScreen.java:156)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.render(SalvagingScreen.java:129)
	at MC//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:110)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$method_47413$328(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$ged000$fancymenu$wrapRenderScreenFancyMenu(GameRenderer.java:11107)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$wrapOperation$ged000$fancymenu$wrapRenderScreenFancyMenu$329(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$hpl000$konkrete$wrapRenderScreenKonkrete(GameRenderer.java:15128)
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at MC//net.minecraft.client.gl.VertexBuffer.drawInternal(VertexBuffer.java:130)
	at MC//net.minecraft.client.gl.VertexBuffer.draw(VertexBuffer.java:123)
	at MC//net.minecraft.client.render.BufferRenderer.drawWithGlobalProgramInternal(BufferRenderer.java:33)
	at MC//net.minecraft.client.render.BufferRenderer.drawWithGlobalProgram(BufferRenderer.java:26)
	at MC//net.minecraft.client.render.RenderLayer.draw(RenderLayer.java:865)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:97)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.method_24213(VertexConsumerProvider.java:76)
	at java.base@17.0.8/java.util.Optional.ifPresent(Optional.java:178)
	at MC//net.minecraft.client.render.VertexConsumerProvider$Immediate.draw(VertexConsumerProvider.java:73)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.renderGuiItem(SalvagingScreen.java:156)
	at dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen.render(SalvagingScreen.java:129)
	at MC//net.minecraft.client.gui.screen.Screen.renderWithTooltip(Screen.java:110)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$method_47413$328(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$ged000$fancymenu$wrapRenderScreenFancyMenu(GameRenderer.java:11107)
	at MC//net.minecraft.client.render.GameRenderer.mixinextras$bridge$wrapOperation$ged000$fancymenu$wrapRenderScreenFancyMenu$329(GameRenderer.java)
	at MC//net.minecraft.client.render.GameRenderer.wrapOperation$hpl000$konkrete$wrapRenderScreenKonkrete(GameRenderer.java:15128)
Mixins in Stacktrace: None found

-- Screen render details --
Details:
	Screen name: dev.shadowsoffire.apotheosis.adventure.affix.salvaging.SalvagingScreen
	Mouse location: Scaled: (258, 108). Absolute: (774.000000, 324.000000)
	Screen size: Scaled: (640, 339). Absolute: (1920, 1017). Scale factor of 3.000000
Stacktrace:
	at MC//net.minecraft.client.render.GameRenderer.render(GameRenderer.java:945)
	at MC//net.minecraft.client.MinecraftClient.render(MinecraftClient.java:1219)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:802)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Affected level --
Details:
	All players: 1 total; [class_746['Splafty'/352, l='ClientLevel', x=791.76, y=62.94, z=21.70]]
	Chunk stats: 1024, 381
	Level dimension: minecraft:overworld
	Level spawn location: World: (128,104,256), Section: (at 0,8,0 in 8,6,16; chunk contains blocks 128,-64,256 to 143,319,271), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)
	Level time: 52014 game time, 52014 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at MC//net.minecraft.client.world.ClientWorld.addDetailsToCrashReport(ClientWorld.java:458)
	at MC//net.minecraft.client.MinecraftClient.addDetailsToCrashReport(MinecraftClient.java:2406)
	at MC//net.minecraft.client.MinecraftClient.run(MinecraftClient.java:821)
	at net.minecraft.client.main.Main.main(Main.java:250)
	at app//net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470)
	at app//net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at app//net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Mixins in Stacktrace: None found

-- Last reload --
Details:
	Reload number: 1
	Reload reason: initial
	Finished: Yes
	Packs: vanilla, fabric, file/Excalibur_V1.20.6.zip, file/Excalibur_V1.19_Mod_Support_GPJ_Build_3.zip, file/Clarent_(20)_1.20.1.zip, file/MMC_Excal, file/STONEBORN+-+1.20-1.20.1+-+V3.2.1.zip, file/STONEBORN-+SBMC+-V3.1-Modded-Compatibility.zip, file/STONEBORN - 1.4-1.20.1 MeiAdditions.zip, file/stoneborn_patches, file/NoBushyLeaves.zip, file/EmbellishedStone-1.20.1-1.0.0.zip, Moonlight Mods Dynamic Assets, seasons:seasonal_lush_caves, presencefootsteps:default_sound_pack, file/Visual Titles.zip, file/[1.4] Enhanced Boss Bars.zip, file/panorama_overrides.zip, file/HTP-Betterarcheology-TranslationPack-v1.0.0.zip, file/HTP-Invoke-TranslationPack-vunknown.zip, file/HTP-Minecells-TranslationPack-v1.0.0.zip, file/HTP-Spell_power-TranslationPack-vunknown.zip, file/EclecticTrove-1.20.1-1.3.0.zip

**Comment by meeprdib** [comment]
Have you modified the modpack in any way, and have you asked the modpack developers about this?

**Comment by Splafty** [comment]
I did not modify the modpack. I'm trying to contact the devs right now.

**Comment by RoyalReject** [comment]
Apotheosis is not on Fabric. You will have to create an issue on the Zenith github tracker.
