### ISSUE TITLE
[1.15.2] Apotheosis causes crash on startup with Anvil Tweaks

### ISSUE THREAD

**Issue by Shandoo94** [Shadows-of-Fire/Apotheosis#179]
Forge Version: 31.2.8
AnvilTweaks: 2.3
Apotheosis 3.1.2

Installing both Apotheosis and AnvilTweaks leads to a crash on startup. It Happens on Forge 3.2.0 as well. AnvilTweaks Dev sais it happens on Apotheosis' side.

Crashlog:

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.client.renderer.RenderType
	at net.minecraft.client.gui.fonts.EmptyGlyph.<init>(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.Font.<clinit>(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontResourceManager.func_212318_b(SourceFile:152) ~[?:?] {re:classloading}
	at net.minecraft.client.gui.fonts.FontResourceManager$$Lambda$3191/1527264715.apply(Unknown Source) ~[?:?] {}
	at java.util.HashMap.computeIfAbsent(HashMap.java:1118) ~[?:1.8.0_51] {}
	at net.minecraft.client.gui.fonts.FontResourceManager.func_211504_a(SourceFile:151) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:408) [?:?] {re:classloading,pl:accesstransformer:B,xf:fml:codechickenlib:IItemRenderer,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(SourceFile:166) [?:?] {re:classloading}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.2.0.jar:31.2] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$458/168555122.call(Unknown Source) [forge-1.15.2-31.2.0.jar:31.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.1.0.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.1.0.jar:?] {}

**Comment by Shadows-of-Fire** [comment]
AnvilTweaks is no longer supported and is incompatible with apoth
