### ISSUE TITLE
1.16.3 crash with anvil tweaks and quark

### ISSUE THREAD

**Issue by Pet-Slime** [Shadows-of-Fire/Apotheosis#245]
[crash-2020-10-22_02.56.23-client.txt](https://github.com/Shadows-of-Fire/Apotheosis/files/5421084/crash-2020-10-22_02.56.23-client.txt)

uploaded crash report. here is the summary 

java.lang.NoClassDefFoundError: Could not initialize class net.minecraft.util.registry.Registry
	at net.minecraft.item.ItemStack.lambda$static$3(ItemStack.java:77) ~[?:?] {re:mixin,re:classloading,xf:fml:apotheosis:apothitemusehook,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.item.ItemStack$$Lambda$1426/1871838170.apply(Unknown Source) ~[?:?] {}
	at com.mojang.serialization.codecs.RecordCodecBuilder.create(RecordCodecBuilder.java:72) ~[datafixerupper-4.0.26.jar:?] {re:classloading}
	at net.minecraft.item.ItemStack.<clinit>(ItemStack.java:76) ~[?:?] {re:mixin,re:classloading,xf:fml:apotheosis:apothitemusehook,pl:mixin:APP:quark.mixins.json:ItemStackMixin,pl:mixin:A}
	at net.minecraft.client.settings.HotbarSnapshot.<init>(SourceFile:13) ~[?:?] {re:classloading}
	at net.minecraft.client.settings.CreativeSettings.<init>(SourceFile:30) ~[?:?] {re:classloading}
	at net.minecraft.client.Minecraft.<init>(Minecraft.java:394) [?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:149) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.3-34.1.23.jar:34.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$470/729375394.call(Unknown Source) [forge-1.16.3-34.1.23.jar:34.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-7.0.1.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-7.0.1.jar:?] {}

**Comment by Shadows-of-Fire** [comment]
Apoth is not compatible with anvil tweaks.
