### ISSUE TITLE
crashing server on startup

### ISSUE THREAD

**Issue by InflamedSebi** [Shadows-of-Fire/Apotheosis#255]
Playing the TNP Limitless 3 pack but apotheosis keeps crashing the server on startup.
If I remove the mod, restart the server and then put it back in, the issue is gone for a while but comes back after a few restarts.

```
[21Nov2020 20:28:58.806] [modloading-worker-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/]: Exception caught during firing event: null
	Index: 4
	Listeners:
		0: NORMAL
		1: ASM: shadows.apotheosis.ench.EnchModule@49d1139d init(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		2: ASM: shadows.apotheosis.spawn.SpawnerModule@10056523 setup(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		3: ASM: shadows.apotheosis.garden.GardenModule@146270dd setup(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		4: ASM: shadows.apotheosis.deadly.DeadlyModule@129acb1f init(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		5: ASM: shadows.apotheosis.potion.PotionModule@550fa0cc init(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		6: ASM: shadows.apotheosis.village.VillageModule@4f2fb29 setup(Lnet/minecraftforge/fml/event/lifecycle/FMLCommonSetupEvent;)V
		7: net.minecraftforge.eventbus.EventBus$$Lambda$2668/954367673@472d2a2
java.lang.ExceptionInInitializerError
	at net.minecraft.item.crafting.Ingredient$TagList.func_199799_a(Ingredient.java:277)
	at net.minecraft.item.crafting.Ingredient.lambda$new$4(Ingredient.java:47)
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90)
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958)
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126)
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230)
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516)
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:47)
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:153)
	at net.minecraft.item.crafting.Ingredient.func_199805_a(Ingredient.java:174)
	at vazkii.psi.api.material.PsimetalToolMaterial.func_200924_f(PsimetalToolMaterial.java:44)
	at shadows.apotheosis.util.NameHelper.getFirstMatch(NameHelper.java:330)
	at shadows.apotheosis.util.NameHelper.computeComment(NameHelper.java:318)
	at shadows.apotheosis.util.NameHelper.load(NameHelper.java:295)
	at shadows.apotheosis.deadly.DeadlyModule.reload(DeadlyModule.java:81)
	at shadows.apotheosis.deadly.DeadlyModule.init(DeadlyModule.java:50)
	at net.minecraftforge.eventbus.ASMEventHandler_1134_DeadlyModule_init_FMLCommonSetupEvent.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297)
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120)
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121)
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175)
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566)
	at net.minecraft.tags.TagCollectionManager.<clinit>(TagCollectionManager.java:8)
	... 32 more

[21Nov2020 20:28:58.811] [modloading-worker-11/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event FMLCommonSetupEvent dispatch for modid apotheosis
java.lang.ExceptionInInitializerError: null
	at net.minecraft.item.crafting.Ingredient$TagList.func_199799_a(Ingredient.java:277) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.lambda$new$4(Ingredient.java:47) ~[?:?]
	at java.util.stream.MatchOps$1MatchSink.accept(MatchOps.java:90) ~[?:1.8.0_265]
	at java.util.Spliterators$ArraySpliterator.tryAdvance(Spliterators.java:958) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.forEachWithCancel(ReferencePipeline.java:126) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:499) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:486) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:230) ~[?:1.8.0_265]
	at java.util.stream.MatchOps$MatchOp.evaluateSequential(MatchOps.java:196) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.anyMatch(ReferencePipeline.java:516) ~[?:1.8.0_265]
	at net.minecraft.item.crafting.Ingredient.<init>(Ingredient.java:47) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_209357_a(Ingredient.java:153) ~[?:?]
	at net.minecraft.item.crafting.Ingredient.func_199805_a(Ingredient.java:174) ~[?:?]
	at vazkii.psi.api.material.PsimetalToolMaterial.func_200924_f(PsimetalToolMaterial.java:44) ~[psi:1.16-88]
	at shadows.apotheosis.util.NameHelper.getFirstMatch(NameHelper.java:330) ~[apotheosis:4.4.1]
	at shadows.apotheosis.util.NameHelper.computeComment(NameHelper.java:318) ~[apotheosis:4.4.1]
	at shadows.apotheosis.util.NameHelper.load(NameHelper.java:295) ~[apotheosis:4.4.1]
	at shadows.apotheosis.deadly.DeadlyModule.reload(DeadlyModule.java:81) ~[apotheosis:4.4.1]
	at shadows.apotheosis.deadly.DeadlyModule.init(DeadlyModule.java:50) ~[apotheosis:4.4.1]
	at net.minecraftforge.eventbus.ASMEventHandler_1134_DeadlyModule_init_FMLCommonSetupEvent.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:297) ~[eventbus-3.0.5-service.jar:?]
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.acceptEvent(FMLModContainer.java:120) ~[forge:35.0]
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:121) ~[forge:?]
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640) [?:1.8.0_265]
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1632) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) [?:1.8.0_265]
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:175) [?:1.8.0_265]
Caused by: java.util.ConcurrentModificationException
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1390) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:482) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:472) ~[?:1.8.0_265]
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708) ~[?:1.8.0_265]
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[?:1.8.0_265]
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:566) ~[?:1.8.0_265]
	at net.minecraft.tags.TagCollectionManager.<clinit>(TagCollectionManager.java:8) ~[?:?]
	... 32 more
[21Nov2020 20:28:58.828] [main/FATAL] [net.minecraftforge.fml.ModLoader/LOADING]: Failed to complete lifecycle event COMMON_SETUP, 1 errors found
[21Nov2020 20:28:58.849] [main/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 7f737c3e-9719-406f-90ab-bd7247e8a91c
[21Nov2020 20:28:58.850] [main/INFO] [STDOUT/]: [net.minecraft.crash.CrashReport:func_85057_a:196]: Negative index in crash report handler (16/18)
[21Nov2020 20:28:58.874] [main/FATAL] [net.minecraftforge.fml.server.ServerModLoader/]: Crash report saved to ./crash-reports/crash-2020-11-21_20.28.58-fml.txt
[21Nov2020 20:28:58.876] [main/FATAL] [net.minecraft.server.Main/]: Failed to start the minecraft server
net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
	Apotheosis (apotheosis) encountered an error during the common_setup event phase
Â§7java.lang.ExceptionInInitializerError: null
]
	at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:263) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:230) ~[forge:?]
	at net.minecraftforge.fml.ModLoader.loadMods(ModLoader.java:205) ~[forge:?]
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:45) ~[forge:?]
	at net.minecraft.server.Main.main(Main.java:95) ~[?:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_265]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_265]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_265]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[?:1.8.0_265]
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[server.jar:35.0]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.6.jar:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.6.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63) [server.jar:?]
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60) [server.jar:?]
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:57) [server.jar:?]

```

**Comment by Shadows-of-Fire** [comment]
That looks like an issue with PSI having an unsafe to resolve static Ingredient, very similar to the issue in MoreVanillaLib resolved by this commit https://github.com/MelanX/MoreVanillaLib/commit/53f263cc7981bb93b2a67f624a2516936ba0ff5a

I cannot fix this issue on my end, its simply unsafe design to create static Ingredients
