### ISSUE TITLE
Enchantment table gui won't open

### ISSUE THREAD

**Issue by LlubNek** [Shadows-of-Fire/Apotheosis#322]
The enchantment table gui won't open when I right click the apotheosis enchanting table.  Nothing happens in game (no crash etc), but an error message appears in the log:
```
[14:08:01] [Server thread/FATAL] [minecraft/ThreadTaskExecutor]: Error executing task on Server
java.lang.NullPointerException: null
	at shadows.apotheosis.ench.table.ApothEnchantContainer.func_75130_a(ApothEnchantContainer.java:164) ~[apotheosis:4.4.1] {re:mixin,re:classloading,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinApotheosisEnchantmentContainer,pl:mixin:A}
	at net.minecraft.inventory.container.EnchantmentContainer$1.func_70296_d(EnchantmentContainer.java:31) ~[?:?] {re:classloading}
	at net.minecraft.inventory.Inventory.func_70299_a(SourceFile:136) ~[?:?] {re:classloading}
	at net.minecraft.inventory.container.Slot.func_75215_d(Slot.java:61) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
	at net.minecraft.inventory.container.EnchantmentContainer.handler$bbc000$open(EnchantmentContainer.java:544) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tabletweaks.mixins.json:EnchantmentContainerMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinEnchantmentContainer,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinEnchantmentScreenHandler,pl:mixin:A}
	at net.minecraft.inventory.container.EnchantmentContainer.<init>(EnchantmentContainer.java:83) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tabletweaks.mixins.json:EnchantmentContainerMixin,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinEnchantmentContainer,pl:mixin:APP:fabrication.mixins.json:i_woina.no_experience.MixinEnchantmentScreenHandler,pl:mixin:A}
	at shadows.apotheosis.ench.table.ApothEnchantContainer.<init>(ApothEnchantContainer.java:69) ~[apotheosis:4.4.1] {re:mixin,re:classloading,pl:mixin:APP:assets/enigmaticlegacy/enigmaticlegacy.mixins.json:MixinApotheosisEnchantmentContainer,pl:mixin:A}
	at shadows.apotheosis.ench.table.ApothEnchantBlock.lambda$getContainer$0(ApothEnchantBlock.java:34) ~[apotheosis:4.4.1] {re:classloading}
	at net.minecraft.inventory.container.SimpleNamedContainerProvider.createMenu(SourceFile:25) ~[?:?] {re:classloading}
	at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:889) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:performant.mixins.json:advancement.ServerPlayerEntityMixin,pl:mixin:APP:tabletweaks.mixins.json:ServerPlayerReserve,pl:mixin:APP:betterendforge.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:endergetic.mixins.json:ServerPlayerEntityMixin,pl:mixin:APP:performant.mixins.json:entity.ServerPlayerEntityMixin,pl:mixin:APP:fabrication.mixins.json:a_fixes.sync_attacker_yaw.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:e_mechanics.obsidian_tears.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:g_weird_tweaks.drop_exp_with_keep_inventory.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.taggable_players.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:b_utility.hide_armor.MixinServerPlayerEntity,pl:mixin:APP:fabrication.mixins.json:_general.sync.MixinServerPlayerEntity,pl:mixin:A}
	at net.minecraft.block.EnchantingTableBlock.func_225533_a_(EnchantingTableBlock.java:83) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morewaterlogging.mixins.json:GetFluidStateMixin,pl:mixin:A}
	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:638) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:assets/passablefoliage/passablefoliage.mixins.json:MixinBlockState,pl:mixin:APP:fabrication.mixins.json:e_mechanics.obsidian_tears.MixinAbstractBlockState,pl:mixin:A}
	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:338) ~[?:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:fabrication.mixins.json:d_minor_mechanics.fire_aspect_is_flint_and_steel.MixinServerPlayerInteractionManager,pl:mixin:APP:fabrication.mixins.json:e_mechanics.pursurvers.MixinServerPlayerInteractionManager,pl:mixin:APP:fabrication.mixins.json:c_tweaks.play_note_blocks_in_creative.MixinServerPlayerInteractionManager,pl:mixin:A}
	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:958) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:fml:astralsorcery:reach_set_server_entity_interact,xf:fml:astralsorcery:allow_entity_interaction,xf:fml:backpacked:creative_inventory_action_fix,pl:mixin:A}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:36) ~[?:?] {re:classloading}
	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(SourceFile:10) ~[?:?] {re:classloading}
	at net.minecraft.network.PacketThreadUtil.lambda$checkThreadAndEnqueue$0(PacketThreadUtil.java:34) ~[?:?] {re:mixin,re:classloading,xf:OptiFine:default}
	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18) ~[?:?] {re:classloading}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:191) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23) ~[?:?] {re:mixin,re:computing_frames,re:classloading}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:734) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:159) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:153) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:717) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:711) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213161_c(ThreadTaskExecutor.java:169) ~[?:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default}
	at net.minecraft.server.MinecraftServer.func_213202_o(MinecraftServer.java:697) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:646) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at net.minecraft.server.MinecraftServer.lambda$startServer$0(MinecraftServer.java:232) ~[?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:structure_gel.mixins.json:MinecraftServerMixin,pl:mixin:APP:betterendforge.mixins.json:MinecraftServerMixin,pl:mixin:APP:jaopca.mixins.json:MinecraftServerMixin,pl:mixin:A}
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242] {}
```

I am using Apotheosis-1.16.3-4.4.1.jar, Minecraft 1.16.5, Forge 36.0.42.
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/6018309/latest.log)

**Comment by Shadows-of-Fire** [comment]
Considering the number of mixins I can see in that stacktrace (and it looks like some are directed at my classes directly) it seems like a mod conflict.  Tables are opening just fine with just apoth enabled

**Comment by choekstr** [comment]
A modded minecraft developer stating, "works fine with just my mod only loaded, not my problem"?  Well that's not very helpful.  If only we could remove all other mods and have the same experience in modded minecraft.  :)

Well I have this problem as well in Enigmatica 6 but as this is modded minecraft and there's bound to be other mods along with apotheosis, it would have been nice to have some insight into the inner workings of the mod and maybe some suggestions as to what type of conflicting mod it would be.  I would think the obvious, anything that touches the enchantment table, but what else?  I see a "inventory.container" in there, so maybe a backpack or chest mod?  There is a 

For others who read this, I know that "Lapis stays in enchanting table" mod in 1.12 used to conflict with apotheosis and wouldn't let the table open (apotheosis overrides the enchantment table to add a new interface so makes sense).  There has also been stated that Vazkii's quark and the tomes conflict with higher enchantment levels but I don't think I believe this.  
I removed "enchantment descriptions" mod but that didn't help.  Next up I will try colouredtooltips mod but after that I can't imagine what else would be conflicting...

1.12 error logs are quite a bit more helpful but it seems that 1.16 logs just don't seem very insightful, IMO so it makes it harder for us to figure out what is conflicting other than "Apotheosis Enchant Container".  There is an "IWorldPosCallable" so maybe a map mod?  

[EDIT: It turns out it was "Table Tweaks" mod, similar function to "lapis stays in enchanting table" in 1.12.  So you can't have both mods, either apotheosis and cool enchants or convenience of table tweaks mod.]

**Comment by Regnosce** [comment]
Disabling lapis reserve mod worked for me. Thank you.
