### ISSUE TITLE
Crash on server start up

### ISSUE THREAD

**Issue by craveful** [Shadows-of-Fire/Apotheosis#342]
Hello, when I added Apotheosis, It seems that my server wont start up. I don't get crash reports but here is the error on my run.bat, I need some help trying to resolve, I downloaded all the dependencies and all.

Update: I found that anvil tweaks was the reason, but is there a way for me to have anvil tweaks still in the mod?

_______________________
[ApotheosisCore]: Patching SharedMonsterAttributes#readAttributeModifier
[ApotheosisCore]: Patching RepairContainer#updateRepairOutput
[ApotheosisCore]: Successfully removed the anvil level cap.
[ApotheosisCore]: Replaced ContainerRepair Enchantment#getMaxLevel #1.
[ApotheosisCore]: Replaced ContainerRepair Enchantment#getMaxLevel #2.
Exception in thread "main" [10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:39)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.run(Launcher.java:82)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.Launcher.main(Launcher.java:66)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:63)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:60)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.server.ServerMain.main(ServerMain.java:57)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.reflect.InvocationTargetException
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at java.lang.reflect.Method.invoke(Unknown Source)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.ThreadGroup:uncaughtException:-1]:         ... 7 more
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:223)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinTransformationHandler.processClass(MixinTransformationHandler.java:121)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.launch.MixinLaunchPlugin.processClass(MixinLaunchPlugin.java:131)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.serviceapi.ILaunchPluginService.processClassWithFlags(ILaunchPluginService.java:154)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.LaunchPluginHandler.offerClassNodeToPlugins(LaunchPluginHandler.java:85)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.ClassTransformer.transform(ClassTransformer.java:120)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.TransformingClassLoader$DelegatedClassLoader.findClass(TransformingClassLoader.java:265)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:136)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at cpw.mods.modlauncher.TransformingClassLoader.loadClass(TransformingClassLoader.java:98)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at java.lang.ClassLoader.loadClass(Unknown Source)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.block.Blocks.<clinit>(Blocks.java:394)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.world.gen.surfacebuilders.SurfaceBuilder.<clinit>(SurfaceBuilder.java:12)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.world.gen.surfacebuilders.ConfiguredSurfaceBuilders.<clinit>(SourceFile:11)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.util.registry.WorldGenRegistries.func_243674_g(WorldGenRegistries.java:33)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.util.registry.WorldGenRegistries.func_243668_a(WorldGenRegistries.java:89)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at java.util.LinkedHashMap.forEach(Unknown Source)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.util.registry.WorldGenRegistries.<clinit>(WorldGenRegistries.java:88)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.util.registry.Registry.<clinit>(Registry.java:464)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.util.registry.Bootstrap.func_151354_b(Bootstrap.java:38)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at net.minecraft.server.Main.main(Main.java:92)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     ... 13 more
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]: Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Constant modifier method uncapRepairCost(I)I in anviltweaks.mixins.json:RepairContainerMixin failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap anviltweaks.refmap.json
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.injection.struct.InjectionInfo.postInject(InjectionInfo.java:408)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinTargetContext.applyInjections(MixinTargetContext.java:1291)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyInjections(MixinApplicatorStandard.java:1042)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:395)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:320)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:345)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:569)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:351)
[10:26:49] [main/INFO] [STDERR/]: [java.lang.Throwable:printStackTrace:-1]:     ... 33 more

**Comment by Shadows-of-Fire** [comment]
you have anvil tweaks installed, which is incompatible.
