### ISSUE TITLE
Unable to turn off Spawner module

### ISSUE THREAD

**Issue by Zygus42** [Shadows-of-Fire/Apotheosis#4]
Change config option:
# If the spawner module is enabled. [default: true]
    B:"Enable Spawner Module"=false

And I can no longer start a new test world, it just sits there "Building Terrain" and I have to crash the game out manually using Task Manager.

I would attach the latest log, but it's a 1GB large textfile !!!!! and won't open :)

**Comment by Zygus42** [comment]
Sorry, forgot to include versions:
forge-1.12.2-14.23.5.2815-installer-win
Apotheosis-1.12.2-1.4.0

**Comment by Shadows-of-Fire** [comment]
Cannot reproduce.  Without a log or crash report, this will be considered a non-issue.

**Comment by Zygus42** [comment]
After many attempts at crashing the game out, I managed to stop the endless loop before it grew too large for my notepad to handle.  This is the pertinent line:
[10:17:26] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: Encountered an unexpected exception
java.lang.NullPointerException: null
	at net.minecraft.tileentity.TileEntityMobSpawner$2.func_188266_a(SourceFile:57) ~[avy$2.class:?]
	at net.minecraftforge.common.util.CompoundDataFixer$1.func_188251_a(CompoundDataFixer.java:76) ~[CompoundDataFixer$1.class:?]
	at net.minecraftforge.common.util.CompoundDataFixer.func_188257_a(CompoundDataFixer.java:89) ~[CompoundDataFixer.class:?]
	at com.pg85.otg.forge.ForgeWorld.attachMetadata(ForgeWorld.java:1311) ~[ForgeWorld.class:?]
	at com.pg85.otg.forge.ForgeWorld.setBlock(ForgeWorld.java:853) ~[ForgeWorld.class:?]
	at com.pg85.otg.customobjects.bo3.RandomBlockFunction.spawn(RandomBlockFunction.java:182) ~[RandomBlockFunction.class:?]
	at com.pg85.otg.customobjects.bo3.BO3.trySpawnAt(BO3.java:202) ~[BO3.class:?]
	at com.pg85.otg.customobjects.CustomObjectCoordinate.spawnWithChecks(CustomObjectCoordinate.java:174) ~[CustomObjectCoordinate.class:?]
	at com.pg85.otg.customobjects.CustomObjectStructure.spawnForChunk(CustomObjectStructure.java:6231) ~[CustomObjectStructure.class:?]
	at com.pg85.otg.generator.resource.CustomStructureGen.spawnInChunk(CustomStructureGen.java:84) ~[CustomStructureGen.class:?]
	at com.pg85.otg.generator.resource.Resource.process(Resource.java:152) ~[Resource.class:?]
	at com.pg85.otg.generator.ObjectSpawner.populate(ObjectSpawner.java:259) ~[ObjectSpawner.class:?]
	at com.pg85.otg.forge.generator.OTGChunkGenerator.func_185931_b(OTGChunkGenerator.java:203) ~[OTGChunkGenerator.class:?]
	at net.minecraft.world.chunk.Chunk.func_186034_a(Chunk.java:1019) ~[axw.class:?]
	at net.minecraft.world.chunk.Chunk.func_186030_a(Chunk.java:999) ~[axw.class:?]
	at net.minecraft.world.gen.ChunkProviderServer.func_186025_d(ChunkProviderServer.java:157) ~[on.class:?]
	at net.minecraft.server.MinecraftServer.func_71222_d(MinecraftServer.java:344) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71247_a(IntegratedServer.java:142) ~[chd.class:?]
	at net.minecraft.server.integrated.IntegratedServer.func_71197_b(IntegratedServer.java:156) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:486) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_191]
[10:17:27] [Server thread/ERROR] [net.minecraft.server.MinecraftServer]: This crash report has been saved to: C:\Users\New\AppData\Roaming\.minecraft\1.12 Reboot\crash-reports\crash-2019-02-18_10.17.27-server.txt

So the problem is with OTG Dregora or OTG itself (Open Terrain Generator), but it only happens when I select False in your config.

Have deleted the endlessly repeated lines and attached the log:
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/2873802/latest.log)

**Comment by Zygus42** [comment]
Problem persists with v1.4.1.

**Comment by knoxhack** [comment]
Problem still present in 1.6.0 :(

**Comment by Shadows-of-Fire** [comment]
You would need to have a different crash report, the original one is no longer possible.
