### ISSUE TITLE
IllegalArgumentException: null at shadows.apotheosis.deadly.affix.AffixEvents.surfaceBosses

### ISSUE THREAD

**Issue by aburone** [Shadows-of-Fire/Apotheosis#438]
I was exploring each time this happened, for what I can understand, a problem when assigning an affix to a mini boss mob
https://hastebin.com/eziqohafej.rb

**Comment by LordBoos** [comment]
I have the same problem. It appears that each time a miniboss is about to be spawned, server crashes.
```
[25Srp2021 15:04:45.675] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: null
	Index: 15
	Listeners:
		0: HIGH
		1: ASM: class me.shedaniel.architectury.event.forge.EventHandlerImplCommon event(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		2: NORMAL
		3: ASM: class net.pavocado.exoticbirds.ForgeEventSubscriber checkSpawns(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		4: ASM: class io.github.how_bout_no.outvoted.world.gen.ModEntitySpawns checkMobs(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		5: ASM: class com.legacy.blue_skies.events.SkiesEvents onEntityCheckSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		6: ASM: class com.teammetallurgy.atum.misc.event.AtumEventListener checkSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		7: ASM: class com.baguchan.enchantwithmob.CommonEventHandler onSpawnEntity(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		8: ASM: class com.minecraftabnormals.environmental.core.other.EnvironmentalEvents onLivingSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		9: ASM: class com.stal111.forbidden_arcanus.event.EntitySpawnListener onCheckSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		10: net.minecraftforge.eventbus.EventBus$$Lambda$2579/998321521@6b3a635e
		11: ASM: class com.baguchan.enchantwithmob.CommonEventHandler onEntitySpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent;)V
		12: ASM: class xratedjunior.betterdefaultbiomes.common.enchantment.EnchantmentEventSubscriber onPlayerTick(Lnet/minecraftforge/event/entity/living/LivingEvent;)V
		13: LOWEST
		14: ASM: class net.xalcon.torchmaster.common.logic.entityblocking.EntityBlockingEventHandler onCheckSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		15: ASM: shadows.apotheosis.deadly.affix.AffixEvents@74017c89 surfaceBosses(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		16: ASM: vazkii.quark.content.world.module.underground.SpiderNestUndergroundBiomeModule@1fcab7e7 onZombieSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		17: ASM: vazkii.quark.content.mobs.module.ForgottenModule@74bd2c66 onSkeletonSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
		18: ASM: mcjty.incontrol.ForgeEventHandlers@667db226 onEntitySpawnEvent(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$CheckSpawn;)V
java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20)
	at shadows.apotheosis.deadly.reload.BossItemManager.getRandomItem(BossItemManager.java:90)
	at shadows.apotheosis.deadly.affix.AffixEvents.surfaceBosses(AffixEvents.java:368)
	at net.minecraftforge.eventbus.ASMEventHandler_141_AffixEvents_surfaceBosses_CheckSpawn.invoke(.dynamic)
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302)
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283)
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201)
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1179)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:172)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124)
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110)
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:670)
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326)
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787)
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642)
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232)
	at java.lang.Thread.run(Thread.java:748)

[25Srp2021 15:04:45.686] [Server thread/FATAL] [net.minecraftforge.common.ForgeMod/]: Preparing crash report with UUID 62d5aaa0-3339-44f1-9b84-3cadedba685d
[25Srp2021 15:04:45.691] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.crash.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:855) ~[?:?]
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:291) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:787) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:642) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:232) ~[?:?]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0-internal]
Caused by: java.lang.IllegalArgumentException
	at net.minecraft.util.WeightedRandom.func_76273_a(SourceFile:20) ~[?:?]
	at shadows.apotheosis.deadly.reload.BossItemManager.getRandomItem(BossItemManager.java:90) ~[apotheosis:4.7.0]
	at shadows.apotheosis.deadly.affix.AffixEvents.surfaceBosses(AffixEvents.java:368) ~[apotheosis:4.7.0]
	at net.minecraftforge.eventbus.ASMEventHandler_141_AffixEvents_surfaceBosses_CheckSpawn.invoke(.dynamic) ~[?:?]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-4.0.0.jar:?]
	at net.minecraftforge.event.ForgeEventFactory.canEntitySpawn(ForgeEventFactory.java:201) ~[forge:?]
	at net.minecraftforge.common.ForgeHooks.canEntitySpawn(ForgeHooks.java:1179) ~[forge:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234966_a_(WorldEntitySpawner.java:172) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234967_a_(WorldEntitySpawner.java:124) ~[?:?]
	at net.minecraft.world.spawner.WorldEntitySpawner.func_234979_a_(WorldEntitySpawner.java:110) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217220_m(ServerChunkProvider.java:670) ~[?:?]
	at net.minecraft.world.server.ServerChunkProvider.func_217207_a(ServerChunkProvider.java:326) ~[?:?]
	at net.minecraft.world.server.ServerWorld.func_72835_b(ServerWorld.java:333) ~[?:?]
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:851) ~[?:?]
	... 5 more
```
