### ISSUE TITLE
Towers generating properly, but all of the towers chests are empty?

### ISSUE THREAD

**Issue by MafiaKitten** [Shadows-of-Fire/Apotheosis#464]
I'm pretty sure this is the source of the issue. 

[19.09 21:12:04] [Server] [WARN] java.lang.NullPointerException: Cannot invoke "net.minecraft.util.ResourceLocation.func_110624_b()" because "minecraft" is null
[19.09 21:12:04] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_16_R3.util.CraftNamespacedKey.fromMinecraft(CraftNamespacedKey.java:24)
[19.09 21:12:04] [Server] [WARN] 	at org.bukkit.craftbukkit.v1_16_R3.event.CraftEventFactory.callLootGenerateEvent(CraftEventFactory.java:1659)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.loot.LootTable.func_216118_a(LootTable.java:116)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.tileentity.LockableLootTileEntity.func_184281_d(LockableLootTileEntity.java:77)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.tileentity.LockableLootTileEntity.createMenu(LockableLootTileEntity.java:145)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.entity.player.ServerPlayerEntity.func_213829_a(ServerPlayerEntity.java:1187)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.block.ChestBlock.func_225533_a_(ChestBlock.java:234)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.block.AbstractBlock$AbstractBlockState.func_227031_a_(AbstractBlock.java:640)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.management.PlayerInteractionManager.func_219441_a(PlayerInteractionManager.java:441)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.network.play.ServerPlayNetHandler.func_184337_a(ServerPlayNetHandler.java:1414)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:38)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.network.play.client.CPlayerTryUseItemOnBlockPacket.func_148833_a(CPlayerTryUseItemOnBlockPacket.java:12)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.network.PacketThreadUtil.lambda$ensureRunningOnSameThread$0(PacketThreadUtil.java:26)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.util.concurrent.TickDelayedTask.run(SourceFile:18)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213166_h(ThreadTaskExecutor.java:153)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.util.concurrent.RecursiveEventLoop.func_213166_h(SourceFile:23)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:942)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_213166_h(MinecraftServer.java:177)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213168_p(ThreadTaskExecutor.java:126)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_213205_aW(MinecraftServer.java:925)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_213168_p(MinecraftServer.java:919)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.util.concurrent.ThreadTaskExecutor.func_213160_bf(ThreadTaskExecutor.java:114)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:1043)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_240802_v_(MinecraftServer.java:821)
[19.09 21:12:04] [Server] [WARN] 	at net.minecraft.server.MinecraftServer.func_240783_a_(MinecraftServer.java:270)
[19.09 21:12:04] [Server] [WARN] 	at java.base/java.lang.Thread.run(Thread.java:832)

**Comment by Shadows-of-Fire** [comment]
craftbukkit is not a supported environment.

**Comment by syorito-hatsuki** [comment]
Why another mods don`t have same problem?

UPD: If break chest all items is dropping correct. So problem only when chest opening
