### ISSUE TITLE
[1.16.5-4.8.3][Mohist] java.lang.NoSuchMethodError: 'void net.minecraft.util.text.Color.<init>(int, java.lang.String)'

### ISSUE THREAD

**Issue by 2A5F** [Shadows-of-Fire/Apotheosis#485]
```
---- Minecraft Crash Report ----
// Ouch. That hurt :(

Time: 11/26/21, 10:33 PM
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:86) ~[forge:?] {re:classloading}
	at net.minecraftforge.fml.server.ServerModLoader.load(ServerModLoader.java:51) ~[forge:?] {re:classloading}
	at net.minecraft.server.Main.main(Main.java:144) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.loading.FMLServerLaunchProvider.lambda$launchService$0(FMLServerLaunchProvider.java:51) ~[mohist-1.16.5-865-server.jar:36.2] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.runLauncher(ServerMain.java:128) [mohist-1.16.5-865-server.jar:?] {}
	at net.minecraftforge.server.ServerMain$Runner.access$100(ServerMain.java:125) [mohist-1.16.5-865-server.jar:?] {}
	at net.minecraftforge.server.ServerMain.main(ServerMain.java:109) [mohist-1.16.5-865-server.jar:?] {}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: main
Stacktrace:
	at shadows.apotheosis.deadly.DeadlyModuleClient$RainbowColor.<init>(DeadlyModuleClient.java:44) ~[apotheosis:4.8.3] {re:classloading}
-- MOD apotheosis --
Details:
	Mod File: Apotheosis-1.16.5-4.8.3.jar
	Failure message: Apotheosis (apotheosis) has failed to load correctly
		java.lang.NoSuchMethodError: 'void net.minecraft.util.text.Color.<init>(int, java.lang.String)'
	Mod Version: 4.8.3
	Mod Issue URL: NOT PROVIDED
	Exception message: java.lang.NoSuchMethodError: 'void net.minecraft.util.text.Color.<init>(int, java.lang.String)'
Stacktrace:
	at shadows.apotheosis.deadly.DeadlyModuleClient$RainbowColor.<init>(DeadlyModuleClient.java:44) ~[apotheosis:4.8.3] {re:classloading}
	at shadows.apotheosis.deadly.affix.LootRarity.<clinit>(LootRarity.java:24) ~[apotheosis:4.8.3] {re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:?] {}
	at java.lang.Class.getEnumConstantsShared(Unknown Source) ~[?:?] {}
	at java.lang.System$2.getEnumConstantsShared(Unknown Source) ~[?:?] {}
	at java.util.EnumMap.getKeyUniverse(Unknown Source) ~[?:?] {}
	at java.util.EnumMap.<init>(Unknown Source) ~[?:?] {}
	at shadows.apotheosis.deadly.DeadlyModule.<clinit>(DeadlyModule.java:63) ~[apotheosis:4.8.3] {re:classloading}
	at shadows.apotheosis.Apotheosis.<init>(Apotheosis.java:99) ~[apotheosis:4.8.3] {re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
	at jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:?] {re:classloading,re:classloading}
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:?] {}
	at java.lang.Class.newInstance(Unknown Source) ~[?:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:82) ~[forge:36.2] {re:classloading}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$4(ModContainer.java:120) ~[forge:?] {re:classloading}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(Unknown Source) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(Unknown Source) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(Unknown Source) ~[?:?] {}


-- System Details --
Details:
	Minecraft Version: 1.16.5
	Minecraft Version ID: 1.16.5
	Mohist Version: 1.16.5-865
	Operating System: Linux (amd64) version 5.4.119-19-0008
	Java Version: 11.0.10, AdoptOpenJDK
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), AdoptOpenJDK
	Memory: 169704000 bytes (161 MB) / 581959680 bytes (555 MB) up to 964689920 bytes (920 MB)
	CPUs: 2
	JVM Flags: 0 total; 
	MCMT: 
		Config Info:
			- Disabled: false
			- World Disabled: false(onPostTick Disabled: false)
			- Entity Disabled: false
			- Env Disabled: false
			- TE Disabled: false
			- SCP Disabled: false

	ModLauncher: 8.0.9+86+master.3cf110c
	ModLauncher launch target: fmlserver
	ModLauncher naming: srg
	ModLauncher services: 
		/mixin-0.8.4.jar mixin PLUGINSERVICE 
		/eventbus-4.0.0.jar eventbus PLUGINSERVICE 
		/mohist-1.16.5-865-server.jar object_holder_definalize PLUGINSERVICE 
		/mohist-1.16.5-865-server.jar runtime_enum_extender PLUGINSERVICE 
		/mohist-1.16.5-865-server.jar capability_inject_definalize PLUGINSERVICE 
		/accesstransformers-3.0.1.jar accesstransformer PLUGINSERVICE 
		/mohist-1.16.5-865-server.jar runtimedistcleaner PLUGINSERVICE 
		/mixin-0.8.4.jar mixin TRANSFORMATIONSERVICE 
		/jmt_mcmt-1.16.5-0.22.87.jar sync_fu TRANSFORMATIONSERVICE 
		/mohist-1.16.5-865-server.jar fml TRANSFORMATIONSERVICE 
	FML: 36.2
	Forge: com.mohistmc:36.2.19
	FML Language Providers: 
		javafml@36.2
		minecraft@1
		kotlinforforge@1.16.0
	Mod List: 
		SaveMyStronghold-1.16.4-1.0.jar          |Save My Stronghold!           |savemystronghold              |1.16.4-1.0          |CREATE_REG|Manifest: NOSIGNATURE
		BetterDungeons-1.16.4-1.2.1.jar            |YUNG's Better Dungeons        |betterdungeons                |1.16.4-1.2.1        |CREATE_REG|Manifest: NOSIGNATURE
		cd4017be_lib-1.16.5-7.1.3.7.jar              |CD4017BE Lib                  |cd4017be_lib                  |7.1.3.7             |CREATE_REG|Manifest: NOSIGNATURE
		jmt_mcmt-1.16.5-0.22.87-modcore.jar   |JMT MCMT                      |jmt_mcmt                      |0.22.87             |CREATE_REG|Manifest: NOSIGNATURE
		Bountiful+Baubles+FORGE-1.16.3-0.0.2.jar  |Bountiful Baubles             |bountifulbaubles              |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		BBOutlineReloaded-2.4-1.16.3-forge.ja|BoundingBoxOutlineReloaded    |bbor                          |2.4-1.16.3          |CREATE_REG|Manifest: NOSIGNATURE
		Comfortable+Nether+4.10.jar                |Comfortable Nether            |comfortable_nether            |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		Mekanism-1.16.5-10.0.24.453.jar            |Mekanism                      |mekanism                      |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		betternether_reforged-1.2.jar             |Better Nether Reforged        |betternether                  |1.2                 |CREATE_REG|Manifest: NOSIGNATURE
		reap-1.16.5-1.0.0.jar                        |Reap Mod                      |reap                          |1.16.5-1.0.0        |CREATE_REG|Manifest: NOSIGNATURE
		BetterCaves-Forge-1.16.4-1.1.2.jar         |YUNG's Better Caves           |bettercaves                   |1.16.4-1.1.2        |CREATE_REG|Manifest: NOSIGNATURE
		Waystones_1.16.5-7.6.4.jar                 |Waystones                     |waystones                     |7.6.4               |CREATE_REG|Manifest: NOSIGNATURE
		FastSuite-1.16.4-1.1.1.jar          |FastSuite                     |fastsuite                     |1.1.1               |CREATE_REG|Manifest: NOSIGNATURE
		Placebo-1.16.5-4.6.1.jar                |Placebo                       |placebo                       |4.6.1               |CREATE_REG|Manifest: NOSIGNATURE
		SimpleStorageNetwork-1.16.5-1.5.0.jar      |Simple Storage Network        |storagenetwork                |1.16.5-1.5.0        |CREATE_REG|Manifest: 1f:47:ac:b1:61:82:96:b8:47:19:16:d2:61:81:11:60:3a:06:4b:61:31:56:7d:44:31:1e:0c:6f:22:5b:4c:ed
		YungsApi-1.16.4-Forge-13.jar                 |YUNG's API                    |yungsapi                      |1.16.4-Forge-13     |CREATE_REG|Manifest: NOSIGNATURE
		champions-forge-1.16.5-2.0.1.8.jar           |Champions                     |champions                     |1.16.5-2.0.1.8      |CREATE_REG|Manifest: NOSIGNATURE
		create-confectionery1.16.5_v1.0.2.jar |Create Confectionery          |create_confectionery          |1.0.2               |CREATE_REG|Manifest: NOSIGNATURE
		Apotheosis-1.16.5-4.8.3.jar                  |Apotheosis                    |apotheosis                    |4.8.3               |ERROR     |Manifest: NOSIGNATURE
		Treasure2TwilightForestLP-mc1.16.5-f|Treasure2TwilightForestLP     |treasure2_twilight_forest_lp  |1.0.0               |CREATE_REG|Manifest: NOSIGNATURE
		sulfuric-1.1.jar                         |Sulfuric                      |sulfuric                      |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		MekanismGenerators-1.16.5-10.0.24.453.ja|Mekanism: Generators          |mekanismgenerators            |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		compactstorage-1.16.5-5.1b17.jar           |Compact Storage               |compactstorage                |1.16.5-5.1b17       |CREATE_REG|Manifest: NOSIGNATURE
		mohist-1.16.5-865-universal.jar                   |Forge                         |forge                         |36.2.19             |CREATE_REG|Manifest: NOSIGNATURE
		twilightforest-1.16.5-4.0.546-universal.jar|The Twilight Forest           |twilightforest                |NONE                |CREATE_REG|Manifest: NOSIGNATURE
		betterendforge-1.16.5-1.6.3.jar           |BetterEnd Forge               |betterendforge                |1.16.5-1.6.3        |CREATE_REG|Manifest: NOSIGNATURE
		DungeonsArise-1.16.5-2.1.47-release.jar  |When Dungeons Arise           |dungeons_arise                |2.1.47              |CREATE_REG|Manifest: NOSIGNATURE
		createplus-1.16.4_v0.3.2.1.jar    |Create Plus                   |createplus                    |1.16.4_v0.3.2.1     |CREATE_REG|Manifest: NOSIGNATURE
		mohist-1.16.5-865-server.jar                      |Minecraft                     |minecraft                     |1.16.5              |CREATE_REG|Manifest: NOSIGNATURE
		cofh_core-1.16.5-1.3.1.jar             |CoFH Core                     |cofh_core                     |1.3.1               |CREATE_REG|Manifest: NOSIGNATURE
		thermal_foundation-1.16.5-1.3.2.jar |Thermal Series                |thermal                       |1.3.2               |CREATE_REG|Manifest: NOSIGNATURE
		FarmersDelight-1.16.5-0.5.1.jar            |Farmer's Delight              |farmersdelight                |1.16.5-0.5.1        |CREATE_REG|Manifest: NOSIGNATURE
		redstonecontrol2-1.16.5-1.0.8.1.jar       |Redstone Control              |rs_ctr2                       |1.0.8.1             |CREATE_REG|Manifest: NOSIGNATURE
		repurposed_structures_forge-3.4.5+1.16.5.ja|Repurposed Structures         |repurposed_structures         |3.4.5+1.16.5        |CREATE_REG|Manifest: NOSIGNATURE
		thermal_innovation-1.16.5-1.3.0.jar |Thermal Innovation            |thermal_innovation            |1.3.0               |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		Treasure2-mc1.16.5-f36.2.0-v1.7.2.jar      |Treasure2                     |treasure2                     |1.7.2               |CREATE_REG|Manifest: NOSIGNATURE
		Botania-1.16.5-420.jar                     |Botania                       |botania                       |1.16.5-420          |CREATE_REG|Manifest: NOSIGNATURE
		flywheel-1.16-0.2.5.jar          |Flywheel                      |flywheel                      |1.16-0.2.5          |CREATE_REG|Manifest: NOSIGNATURE
		steampowered-1.16.5-1.1.9.jar       |Create: Steam Powered         |steampowered                  |1.16.5-1.1.9        |CREATE_REG|Manifest: NOSIGNATURE
		create-mc1.16.5_v0.3.2g.jar                |Create                        |create                        |v0.3.2g             |CREATE_REG|Manifest: NOSIGNATURE
		curios-forge-1.16.5-4.0.5.3.jar        |Curios API                    |curios                        |1.16.5-4.0.5.3      |CREATE_REG|Manifest: NOSIGNATURE
		eidolon-0.2.7.jar                            |Eidolon                       |eidolon                       |0.2.7               |CREATE_REG|Manifest: NOSIGNATURE
		Patchouli-1.16.4-53.2.jar            |Patchouli                     |patchouli                     |1.16.4-53.2         |CREATE_REG|Manifest: NOSIGNATURE
		Mantle-1.16.5-1.6.127.jar               |Mantle                        |mantle                        |1.6.127             |CREATE_REG|Manifest: NOSIGNATURE
		ftb-backups-2.1.2.2.jar                    |FTB Backups                   |ftbbackups                    |2.1.2.2             |CREATE_REG|Manifest: NOSIGNATURE
		thermal_cultivation-1.16.5-1.3.0.jar|Thermal Cultivation           |thermal_cultivation           |1.3.0               |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		thermal_expansion-1.16.5-1.3.0.jar  |Thermal Expansion             |thermal_expansion             |1.3.0               |CREATE_REG|Manifest: 75:0b:cc:9b:64:2e:9b:c4:41:d1:95:00:71:ee:87:1a:b3:5e:4b:da:8e:e8:39:00:fd:5d:e5:9c:40:42:33:09
		GottschCore-mc1.16.5-f36.1.0-v1.4.0.ja|GottschCore                   |gottschcore                   |1.4.0               |CREATE_REG|Manifest: NOSIGNATURE
		EnigmaticLegacy-2.11.6.jar                 |Enigmatic Legacy              |enigmaticlegacy               |2.11.6              |CREATE_REG|Manifest: NOSIGNATURE
		worldedit-mod-7.2.5-dist.jar                |WorldEdit                     |worldedit                     |7.2.5+57d5ac9       |CREATE_REG|Manifest: NOSIGNATURE
		MekanismTools-1.16.5-10.0.24.453.jar     |Mekanism: Tools               |mekanismtools                 |10.0.24             |CREATE_REG|Manifest: NOSIGNATURE
		appleskin-forge-mc1.16.x-2.2.0.jar          |AppleSkin                     |appleskin                     |mc1.16.4-2.2.0      |CREATE_REG|Manifest: NOSIGNATURE
		architectury-1.25.36-forge.jar      |Architectury                  |architectury                  |1.25.36             |CREATE_REG|Manifest: NOSIGNATURE
		ExtraBotany-r1.2-68.jar            |ExtraBotany                   |extrabotany                   |1.0                 |CREATE_REG|Manifest: NOSIGNATURE
		ferritecore-2.1.0-forge.jar          |Ferrite Core                  |ferritecore                   |2.1.0               |CREATE_REG|Manifest: 41:ce:50:66:d1:a0:05:ce:a1:0e:02:85:9b:46:64:e0:bf:2e:cf:60:30:9a:fe:0c:27:e0:63:66:9a:84:ce:8a
		SoL-Carrot-1.16.5-1.10.1.jar              |Spice of Life: Carrot Edition |solcarrot                     |1.16.5-1.10.1       |CREATE_REG|Manifest: NOSIGNATURE
		cloth-config-4.12.41-forge.jar               |Cloth Config v4 API           |cloth-config                  |4.12.41             |CREATE_REG|Manifest: NOSIGNATURE
		smallships-1.16.5-1.10.1.jar                 |Small Ships Mod               |smallships                    |1.10.1              |CREATE_REG|Manifest: NOSIGNATURE
		observable-0.1.3-forge.jar               |Observable                    |observable                    |0.1.3               |CREATE_REG|Manifest: NOSIGNATURE
	Crash Report UUID: dd1d09fd-5727-4c52-afdc-1873221d2f9d
	CraftBukkit Information: 
   Running: 
   Failed to handle CraftCrashReport: craftbukkit not runs

```

**Comment by Shadows-of-Fire** [comment]
That's a mohist problem
