### ISSUE TITLE
Modded anvils are broken with Apotheosis

### ISSUE THREAD

**Issue by JaisDK** [Shadows-of-Fire/Apotheosis#578]
as discussed on Discord

**Comment by JaisDK** [comment]
Caused by: java.lang.NullPointerException
    at java.util.Objects.requireNonNull(Objects.java:208) ~[?:?] {}
    at java.util.Optional.of(Optional.java:113) ~[?:?] {}
    at net.minecraft.world.inventory.ContainerLevelAccess$2.evaluate(ContainerLevelAccess.java:22) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:classloading}
    at shadows.apotheosis.ench.EnchModuleEvents.applyUnbreaking(EnchModuleEvents.java:140) ~[apotheosis-313970-3781524_mapped_official_1.18.2.jar%2386!/:5.3.5] {re:classloading}
    at net.minecraftforge.eventbus.ASMEventHandler_100_EnchModuleEvents_applyUnbreaking_AnvilRepairEvent.invoke(.dynamic) ~[?:?] {}
    at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:85) ~[eventbus-5.0.7.jar%239!/:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:302) ~[eventbus-5.0.7.jar%239!/:?] {}
    at net.minecraftforge.eventbus.EventBus.post(EventBus.java:283) ~[eventbus-5.0.7.jar%239!/:?] {}
    at net.minecraftforge.common.ForgeHooks.onAnvilRepair(ForgeHooks.java:674) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2375%2381!/:?] {re:classloading}
    at net.minecraft.world.inventory.AnvilMenu.onTake(AnvilMenu.java:56) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:apotheosis:ench_info_redirects,re:classloading,pl:accesstransformer:B,xf:fml:apotheosis:ench_info_redirects,pl:mixin:APP:apotheosis.mixins.json:AnvilMenuMixin,pl:mixin:A}
    at net.minecraft.world.inventory.ItemCombinerMenu$2.onTake(ItemCombinerMenu.java:59) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:classloading}
    at net.minecraft.world.inventory.AbstractContainerMenu.lambda$doClick$3(AbstractContainerMenu.java:418) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:A}
    at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {}
    at net.minecraft.world.inventory.AbstractContainerMenu.doClick(AbstractContainerMenu.java:416) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:A}
    at net.minecraft.world.inventory.AbstractContainerMenu.clicked(AbstractContainerMenu.java:295) ~[forge-1.18.2-40.1.21_mapped_official_1.18.2.jar%2376!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:placebo.mixins.json:AbstractContainerMenuInvoker,pl:mixin:A}

**Comment by JaisDK** [comment]
Any progress on this? It turns modded anvils into dupe machines which is a little annoying.
