### ISSUE TITLE
Bosses or something

### ISSUE THREAD

**Issue by Fortist** [Shadows-of-Fire/Apotheosis#6]
I got this crash while wandering around
```
---- Minecraft Crash Report ----
// I blame Dinnerbone.

Time: 2019-02-19 10:10:21 EST
Description: Exception in server tick loop

java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.getRandomItem(SourceFile:18)
    at net.minecraft.util.WeightedRandom.getRandomItem(SourceFile:37)
    at shadows.deadly.gen.BossFeature.generate(BossFeature.java:34)
    at shadows.deadly.gen.WorldGenerator.run(WorldGenerator.java:37)
    at shadows.deadly.gen.WorldGenerator.generate(WorldGenerator.java:29)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:990)
    at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:110)
    at net.minecraftforge.common.chunkio.ChunkIOExecutor.tick(ChunkIOExecutor.java:150)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:728)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```

Also, Im getting random lightning and constant "Isquid Sheeperern" or whatever the name is dying or suffocating in the walls. While roaming around I found a skeleton full of potion effects standing on top of a mountain in full armor with half a heart bugging out. For the moment, Im gonna disable the deadly part and see what takes.

**Comment by Shadows-of-Fire** [comment]
What version of Apotheosis are you running?  This crash was common in an older version (the latest is 1.4.2).

As for them randomly dying in the walls and whatnot... Yeah, that's not supposed to happen.

**Comment by Fortist** [comment]
Whoops, It seems like I was down a version, I guess I missed the update. But I will check back if it's still borked.

**Comment by Fortist** [comment]
Huh. Go something similar but with Ice and Fire.
```
---- Minecraft Crash Report ----
// Don't be sad. I'll do better next time, I promise!

Time: 2019-02-19 22:36:09 EST
Description: Ticking entity

java.lang.IllegalArgumentException
    at net.minecraft.util.WeightedRandom.getRandomItem(SourceFile:18)
    at net.minecraft.util.WeightedRandom.getRandomItem(SourceFile:37)
    at shadows.deadly.gen.BossFeature.generate(BossFeature.java:34)
    at shadows.deadly.gen.WorldGenerator.run(WorldGenerator.java:37)
    at shadows.deadly.gen.WorldGenerator.generate(WorldGenerator.java:29)
    at net.minecraftforge.fml.common.registry.GameRegistry.generateWorld(GameRegistry.java:167)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:1020)
    at net.minecraft.world.chunk.Chunk.populate(Chunk.java:980)
    at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:157)
    at net.minecraft.world.World.getChunk(World.java:310)
    at net.minecraft.world.World.getChunk(World.java:305)
    at net.minecraft.world.World.getBlockState(World.java:911)
    at net.minecraft.world.World.rayTraceBlocks(World.java:1080)
    at net.minecraft.world.World.rayTraceBlocks(World.java:930)
    at com.github.alexthe666.iceandfire.entity.EntityHippogryph.isTargetBlocked(EntityHippogryph.java:983)
    at com.github.alexthe666.iceandfire.entity.DragonUtils.getBlockInViewHippogryph(DragonUtils.java:134)
    at com.github.alexthe666.iceandfire.entity.ai.HippogryphAIAirTarget.getNearbyAirTarget(HippogryphAIAirTarget.java:84)
    at com.github.alexthe666.iceandfire.entity.ai.HippogryphAIAirTarget.findAirTarget(HippogryphAIAirTarget.java:76)
    at com.github.alexthe666.iceandfire.entity.ai.HippogryphAIAirTarget.shouldExecute(HippogryphAIAirTarget.java:42)
    at net.minecraft.entity.ai.EntityAIBase.shouldContinueExecuting(SourceFile:9)
    at net.minecraft.entity.ai.EntityAITasks.canContinue(SourceFile:136)
    at net.minecraft.entity.ai.EntityAITasks.onUpdateTasks(SourceFile:108)
    at net.minecraft.entity.EntityLiving.updateEntityActionState(EntityLiving.java:763)
    at net.minecraft.entity.EntityLivingBase.onLivingUpdate(EntityLivingBase.java:2359)
    at net.minecraft.entity.EntityLiving.onLivingUpdate(EntityLiving.java:577)
    at net.minecraft.entity.EntityAgeable.onLivingUpdate(EntityAgeable.java:178)
    at net.minecraft.entity.passive.EntityAnimal.onLivingUpdate(SourceFile:43)
    at com.github.alexthe666.iceandfire.entity.EntityHippogryph.onLivingUpdate(EntityHippogryph.java:714)
    at net.minecraft.entity.EntityLivingBase.onUpdate(EntityLivingBase.java:2179)
    at net.minecraft.entity.EntityLiving.onUpdate(EntityLiving.java:295)
    at com.github.alexthe666.iceandfire.entity.EntityHippogryph.onUpdate(EntityHippogryph.java:910)
    at net.minecraft.world.World.updateEntityWithOptionalForce(World.java:1993)
    at net.minecraft.world.WorldServer.updateEntityWithOptionalForce(WorldServer.java:832)
    at net.minecraft.world.World.updateEntity(World.java:1955)
    at net.minecraft.world.World.redirect$updateEntity$zcd000(World.java:4117)
    at net.minecraft.world.World.updateEntities(World.java:1759)
    at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613)
    at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:767)
    at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668)
    at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:185)
    at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526)
    at java.lang.Thread.run(Unknown Source)
```
