### ISSUE TITLE
Enchantment UI won't open, Server posts the following error upon rightclick.

### ISSUE THREAD

**Issue by GummyWyrmDeluxe** [Shadows-of-Fire/Apotheosis#607]
Hey I hope this is the right place to put this, here's the error the server prints below. Thanks.

`[14:29:44] [Server thread/ERROR]: Failed to handle packet net.minecraft.class_2885@2270fbec, suppressing error
java.lang.NullPointerException: Cannot invoke "safro.apotheosis.util.FloatReferenceHolder.set(float)" because "this.eterna" is null
        at safro.apotheosis.ench.table.ApothEnchantContainer.lambda$gatherStats$3(ApothEnchantContainer.java:251) ~[apotheosis-0.2.83.jar:?]
        at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[server-intermediary.jar:?]
        at safro.apotheosis.ench.table.ApothEnchantContainer.gatherStats(ApothEnchantContainer.java:228) ~[apotheosis-0.2.83.jar:?]
        at safro.apotheosis.ench.table.ApothEnchantContainer.lambda$slotsChanged$1(ApothEnchantContainer.java:163) ~[apotheosis-0.2.83.jar:?]
        at net.minecraft.class_3914$2.method_17395(class_3914.java:22) ~[server-intermediary.jar:?]
        at safro.apotheosis.ench.table.ApothEnchantContainer.method_7609(ApothEnchantContainer.java:160) ~[apotheosis-0.2.83.jar:?]
        at net.minecraft.class_1718$1.method_5431(class_1718.java:32) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.redirect$cha000$fabric_redirectMarkDirty(class_1277.java:543) ~[server-intermediary.jar:?]
        at net.minecraft.class_1277.method_5447(class_1277.java:140) ~[server-intermediary.jar:?]
        at net.minecraft.class_1735.method_7673(class_1735.java:61) ~[server-intermediary.jar:?]
        at net.minecraft.class_1718.handler$clk000$open(class_1718.java:1530) ~[server-intermediary.jar:?]
        at net.minecraft.class_1718.<init>(class_1718.java:92) ~[server-intermediary.jar:?]
        at safro.apotheosis.ench.table.ApothEnchantContainer.<init>(ApothEnchantContainer.java:62) ~[apotheosis-0.2.83.jar:?]
        at net.minecraft.class_2331.md02b8e6$lambda$apothEnchMenu$0$0(class_2331.java:1039) ~[server-intermediary.jar:?]
        at net.minecraft.class_747.createMenu(class_747.java:25) ~[server-intermediary.jar:?]
        at net.minecraft.class_3222.method_17355(class_3222.java:1031) ~[server-intermediary.jar:?]
        at net.minecraft.class_2331.method_9534(class_2331.java:87) ~[server-intermediary.jar:?]
        at net.minecraft.class_4970$class_4971.method_26174(class_4970.java:939) ~[server-intermediary.jar:?]
        at net.minecraft.class_3225.method_14262(class_3225.java:336) ~[server-intermediary.jar:?]
        at net.minecraft.class_3244.method_12046(class_3244.java:1081) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_12547(class_2885.java:30) ~[server-intermediary.jar:?]
        at net.minecraft.class_2885.method_11054(class_2885.java:8) ~[server-intermediary.jar:?]
        at net.minecraft.class_2600.method_11072(class_2600.java:22) ~[server-intermediary.jar:?]
        at net.minecraft.class_3738.run(class_3738.java:18) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_18859(class_1255.java:157) ~[server-intermediary.jar:?]
        at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_24306(MinecraftServer.java:808) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_18859(MinecraftServer.java:165) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_16075(class_1255.java:131) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:790) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:784) ~[server-intermediary.jar:?]
        at net.minecraft.class_1255.method_5383(class_1255.java:116) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_16208(MinecraftServer.java:768) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:701) ~[server-intermediary.jar:?]
        at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273) ~[server-intermediary.jar:?]
        at java.lang.Thread.run(Unknown Source) [?:?]`

![image](https://user-images.githubusercontent.com/47509490/181937007-c69ad0c8-f18f-44bd-8543-a1fc6f29e73c.png)

**Comment by GummyWyrmDeluxe** [comment]
Oh I should mention this is on Fabric, latest version on MC 1.18.2 !

**Comment by Shadows-of-Fire** [comment]
> Fabric
not supported
