### ISSUE TITLE
"Limited Enchantability" on EVERYTHING. (1.18.2)

### ISSUE THREAD

**Issue by 4AC11** [Shadows-of-Fire/Apotheosis#611]
Before anyone responds to this, yes, I have seen the other post about limited enchantability, this is _not_ the same issue. Additionally, the solution given in that issue wouldn't work here as I cannot enchant any item, and therefore cannot reroll my enchantment seed.

Every time I go to enchant something, at any amount of enchanting power, I get the "limited enchantability" message. Even when using the most enchantable tools in vanilla (gold) or a plain book that should be able to have any enchantment. 

My only possible theory is that it could have something to do with other mod's enchantments, since I just added Malum and Soul Shards to the pack when this started happening (I'll reply to this post with further testing after posting). Maybe too many mods adding enchantments has caused some sort of overflow issue? I really have no idea. 

![image](https://user-images.githubusercontent.com/97819008/183331893-01a2753b-d1b7-4d4f-9d30-729b1852daf0.png)
![image](https://user-images.githubusercontent.com/97819008/183331919-3e2b4736-ddeb-47e4-bde4-d3b3fc0800ef.png)

**Comment by Shadows-of-Fire** [comment]
Any chance you could try with a different setup?  Mainly wondering what happens if you squish your quanta value down to zero (and potentially also your arcana).

I find it bizzare that none of the enchantments are satisfying the criteria of a level 33, 74, or 96 enchantment with any item unless some mod was just blowing everything up.

If there was a substantial issue, you would have a log error (probably on the server side).

**Comment by 4AC11** [comment]
The game just... crashed? Kind of? It kicked me out of my singleplayer world with the text "server closed". It also generated a crashlog file with this in it:
[23:19:02] [Render thread/INFO]: [CHAT] Gave 64    [Lapis Lazuli] to 4AC11
[23:19:04] [Server thread/ERROR]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundContainerClickPacket@80771d6, suppressing error
net.minecraft.ReportedException: Container click
	at net.minecraft.world.inventory.AbstractContainerMenu.m_150399_(AbstractContainerMenu.java:309) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.network.ServerGamePacketListenerImpl.m_5914_(ServerGamePacketListenerImpl.java:1309) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:56) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.network.protocol.game.ServerboundContainerClickPacket.m_5797_(ServerboundContainerClickPacket.java:12) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.TickTask.run(TickTask.java:18) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:799) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:164) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:782) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:776) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:762) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:689) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at net.minecraft.server.MinecraftServer.m_177918_(MinecraftServer.java:261) ~[client-1.18.2-20220404.173914-srg.jar%23226!/:?]
	at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.NullPointerException
[23:21:22] [Server thread/INFO]: Saving and pausing game...

I can't make any heads or tails of it, but maybe it means something to you?

**Comment by Shadows-of-Fire** [comment]
Pull the full `debug.log` from the run where that crash occurred, the actual error is buried deeper.

**Comment by 4AC11** [comment]
Where do I find that? I'm taking this from the modpack's latest.log file in the logs folder.

**Comment by Shadows-of-Fire** [comment]
`<root>/logs/debug.log`, should be right next to latest.log, though latest might do if debug isn't present.  I know curseforge has a history of not generating the debug log, annoyingly.

**Comment by 4AC11** [comment]
Ah, that appears to be the case, however latest.log does seem to include my PC's file path, and thus my real full name, about 170 times. I've taken the liberty of removing them in notepad.
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9278524/latest.log)

**Comment by 4AC11** [comment]
In other news, my testing in another mod profile has revealed that it may very well be Malum having something to do with the issue, as in a profile with only malum and apotheosis, vanilla items are now able to be enchanted, and even a few malum items (picture 2), but scythes are showing the limited enchantability text.

![image](https://user-images.githubusercontent.com/97819008/183334752-2795fcbd-a6e6-48f4-8c13-4941d955829d.png)
![image](https://user-images.githubusercontent.com/97819008/183334819-aef06ba4-a876-4080-9a21-8f5cf9b303e2.png)
![image](https://user-images.githubusercontent.com/97819008/183334847-9a46eea7-b492-47a6-b559-aeb9b7d20061.png)

**Comment by 4AC11** [comment]
Nevermind! It turns out the limited enchantability message on the scythe was a legitimate message telling me I needed more shelves! 
![image](https://user-images.githubusercontent.com/97819008/183336338-38e51860-fde2-44fb-a59f-f31f51ee67e9.png)

So I guess Malum isn't the issue? Is it really just having too many enchantments in the pack, or something totally different?

**Comment by Shadows-of-Fire** [comment]
No, if you're seeing that exception it means you have something modifying the menu incompatibly.  Do you have something else that adds keeping lapis or would otherwise change the table?

**Comment by 4AC11** [comment]
No, I already has issues with that kind of thing previously so I made sure to remove any mods that had that feature. Unless some mod is doing it without me knowing, which seems unlikely since like I said the only mods I added (before the issue started happening) were Malum and Soul Shards, which I just tested with apotheosis (in the above post) and they worked fine. 

I'll take a look at some of the mods though just to make sure nothing's messing with the Table.

**Comment by 4AC11** [comment]
Wait! it seems there is a mod that makes lapis stay in the table... Though I have no idea which mod is doing it at the minute. I'll keep looking, but hopefully once I find and remove the offender, this will fix the problem

a TL;DR to future googlers: remove any mods that modify the enchanting table or make lapis stay in the table while using Apotheosis!

**Comment by Shadows-of-Fire** [comment]
Well, no, apoth does it, so it's expected that it does.  It's if you have something *else* doing it, it becomes bad.

**Comment by 4AC11** [comment]
Oh! I didn’t even know about that feature... in that case I’m still stumped as to what’s actually causing the problem, since none of my other mods do that.

I did notice that I the pack includes Attributefix though, could that have something to do with it?

**Comment by Shadows-of-Fire** [comment]
No, attributes aren't any portion of the Enchanting Table.

**Comment by 4AC11** [comment]
Alright. I really have no idea then. Are there any other logs or files I could send that could help to diagnose the problem?

**Comment by Shadows-of-Fire** [comment]
Realistically just the debug.log, but since CF doesn't generate it you'd have to run using another launcher to get it.

I'm not even sure if the debug would contain the exception, but the latest is truncating the exception to just the raw exception (without the stacktrace), which isn't usable.

**Comment by 4AC11** [comment]
I see... I’ll mess around with the enchantments and mods in the pack tomorrow, hopefully I can find a solution.

**Comment by 4AC11** [comment]
I've found it! It turns out the [Soul Ice](https://www.curseforge.com/minecraft/mc-mods/soul-ice) mod was causing the problem. I know that it adds two enchantments (which were both disabled in my modpack), so I'm not entirely sure what the exact conflict is. I'll go ahead and make an issue on the Soul Ice github to inform the creator of this incompatibility.

**Comment by Shadows-of-Fire** [comment]
I did a casual search of their codebase and I didn't see anything that would obviously cause such a problem, so I'm not sure.

**Comment by 4AC11** [comment]
Hmm.. I don't really know then. Removing the mod fixed the issue, though. The only thing I can think of is that maybe it really was a problem of just having too many enchantments in the pack??
