### ISSUE TITLE
loading error 

### ISSUE THREAD

**Issue by Vdsj25** [Shadows-of-Fire/Apotheosis#620]
the game starts fine but when loading in a world it gives an error of "failed to load data pack" and then doesnt want start safe mode.
[latest.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9386952/latest.log)

**Comment by Vdsj25** [comment]
![Schermafbeelding 2022-08-20 131713](https://user-images.githubusercontent.com/60917796/185743524-0f367672-bb72-4597-aa60-d10d41f1636f.png)
this is the error screen

**Comment by tharrmeehan** [comment]
Can confirm, happening with Apotheosis-1.18.2-5.4.0 and Placebo-1.18.2-6.6.0, fixed when downgrading Placebo.
[debug.log](https://github.com/Shadows-of-Fire/Apotheosis/files/9387075/debug.log)

**Comment by Remingusu** [comment]
I have the same problem with Apotheosis-1.18.2-5.4.1 and Placebo-1.18.2-6.6.0 when running my server.
Like @tharrmeehan, fixed when running with Placebo-1.18.2-6.5.3.

**Comment by Shibva** [comment]
Can Confirm this as well

and have located the issue in the log
```
12:10:04] [Render thread/WARN]: Failed to load datapacks, can't proceed with server load
java.util.concurrent.ExecutionException: java.lang.AbstractMethodError: Receiver class shadows.apotheosis.ench.table.EnchantingStatManager$$Lambda$24794/0x0000000802fff418 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object read(com.google.gson.JsonObject)' of interface shadows.placebo.json.SerializerBuilder$JsonDeserializer.
	at java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:396) ~[?:?]
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:2073) ~[?:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2082) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.Minecraft.doLoadLevel(Minecraft.java:1908) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.Minecraft.m_205185_(Minecraft.java:1876) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.m_100972_(CreateWorldScreen.java:246) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.screens.worldselection.CreateWorldScreen.lambda$init$13(CreateWorldScreen.java:195) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.components.Button.m_5691_(Button.java:40) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.components.AbstractButton.m_5716_(AbstractButton.java:16) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.components.AbstractWidget.m_6375_(AbstractWidget.java:111) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.components.events.ContainerEventHandler.m_6375_(ContainerEventHandler.java:27) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.MouseHandler.m_168084_(MouseHandler.java:88) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.gui.screens.Screen.m_96579_(Screen.java:528) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.MouseHandler.m_91530_(MouseHandler.java:85) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.MouseHandler.m_168091_(MouseHandler.java:185) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.execute(BlockableEventLoop.java:118) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.MouseHandler.m_91565_(MouseHandler.java:184) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at org.lwjgl.glfw.GLFWMouseButtonCallbackI.callback(GLFWMouseButtonCallbackI.java:36) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at org.lwjgl.system.JNI.invokeV(Native Method) ~[lwjgl-3.2.2.jar%2344!/:build 10]
	at org.lwjgl.glfw.GLFW.glfwPollEvents(GLFW.java:3101) ~[lwjgl-glfw-3.2.2.jar%2348!/:build 10]
	at com.mojang.blaze3d.systems.RenderSystem.m_69495_(RenderSystem.java:202) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at com.mojang.blaze3d.platform.Window.m_85435_(Window.java:442) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1067) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:664) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.main.Main.main(Main.java:205) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:31) ~[fmlloader-1.18.2-40.1.73.jar%2317!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-9.1.3.jar%235!/:?]
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:149) [bootstraplauncher-1.0.0.jar:?]
Caused by: java.lang.AbstractMethodError: Receiver class shadows.apotheosis.ench.table.EnchantingStatManager$$Lambda$24794/0x0000000802fff418 does not define or inherit an implementation of the resolved method 'abstract java.lang.Object read(com.google.gson.JsonObject)' of interface shadows.placebo.json.SerializerBuilder$JsonDeserializer.
	at shadows.placebo.json.SerializerBuilder$Serializer.read(SerializerBuilder.java:147) ~[Placebo-1.18.2-6.6.0.jar%23184!/:6.6.0]
	at shadows.placebo.json.PlaceboJsonReloadListener.lambda$apply$0(PlaceboJsonReloadListener.java:98) ~[Placebo-1.18.2-6.6.0.jar%23184!/:6.6.0]
	at java.util.HashMap.forEach(HashMap.java:1421) ~[?:?]
	at shadows.placebo.json.PlaceboJsonReloadListener.apply(PlaceboJsonReloadListener.java:86) ~[Placebo-1.18.2-6.6.0.jar%23184!/:6.6.0]
	at shadows.placebo.json.PlaceboJsonReloadListener.m_5787_(PlaceboJsonReloadListener.java:49) ~[Placebo-1.18.2-6.6.0.jar%23184!/:6.6.0]
	at net.minecraft.server.packs.resources.SimplePreparableReloadListener.m_10789_(SimplePreparableReloadListener.java:13) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:718) ~[?:?]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482) ~[?:?]
	at net.minecraft.server.packs.resources.SimpleReloadInstance.m_143940_(SimpleReloadInstance.java:69) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:198) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:163) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:176) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	at net.minecraft.client.Minecraft.m_205125_(Minecraft.java:2081) ~[client-1.18.2-20220404.173914-srg.jar%23237!/:?]
	... 35 more
[12:33:01] [Render thread/INFO]: Stopping!```

**Comment by Shibva** [comment]
I was told its missing something and as a result is making it unusable

**Comment by Shadows-of-Fire** [comment]
Placebo 6.6.0 is incompatible with apoth 5.4.1, just use the older version of placebo in the meantime

**Comment by arzadu** [comment]
> Placebo 6.6.0 is incompatible with apoth 5.4.1, just use the older version of placebo in the meantime

Which version of placebo should be used? I just tried 6.5.3 and got the same error

relevant log paste [here](https://pastebin.com/Mtk67Vnx)

**Comment by Shadows-of-Fire** [comment]
That paste shows you are still using 6.6.0.  6.5.3 will work.
