### ISSUE TITLE
Crash upon hitting an Apotheosis boss with an enchanted affix wooden sword?

### ISSUE THREAD

**Issue by n0valey** [Shadows-of-Fire/Apotheosis#791]
This is one of the parts to a complex problem, me and my friends are playing on a modded minecraft server. The main mods that seem to be the offenders are your mod(Apotheosis) and the Origins for forge mod. 
My friend has crashed twice during the same circumstances, he is of phantom origin and was hitting an apotheosis boss from inside the ground with his current wooden sword, (him crashing while being in the ground, then disconnecting him in the ground ended up corrupting his player data. Probably from origins maybe not having a failsafe for when a phantom origin player logs out in the ground? I am not a mod developer, only a modpack creator)
I'm not 100% sure what specifically is crashing, but my friend is willing to test it again to get a capture of the logs, and I'll provide a screenshot of the sword in question. It was a different boss both times, so I'm not sure how much the type of boss plays into the issue. 
(I also have a suggestion for your mod, but I'll save it for a different post!)
![image](https://user-images.githubusercontent.com/126108875/220759642-92c76e4c-c2b3-4a7f-aea4-9e7793062adf.png)

**Comment by n0valey** [comment]
Server thread/[WARN] [minecraft/ServerConnectionListener]: Failed to handle packet for /99.242.209.236:53466
22.02 22:02:44 [Server] [INFO] net.minecraft.ReportedException: Ticking player
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:510) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.network.ServerGamePacketListenerImpl.m_9933_(ServerGamePacketListenerImpl.java:264) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,re:classloading,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.network.Connection.m_129483_(Connection.java:248) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.network.ServerConnectionListener.m_9721_(ServerConnectionListener.java:143) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:880) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:292) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:tombstone.mixins.json:DedicatedServerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:citadel.mixins.json:MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:APP:crafttweaker.mixins.json:common.access.server.AccessMinecraftServer,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at java.lang.Thread.run(Thread.java:831) [?:?] {re:mixin}
22.02 22:02:44 [Server] [INFO] Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.entity.player.Player.m_5647_()" because "p_36169_" is null
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.player.Player.m_7099_(Player.java:881) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:additionalentityattributes.mixins.json:common.DigSpeedMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:apoli.mixins.json:PlayerEntityMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_7099_(ServerPlayer.java:677) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.sweenus.simplyswords.util.HelperMethods.checkFriendlyFire(HelperMethods.java:48) ~[simplyswords-forge-1.40-1.19.2.jar%23213!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.sweenus.simplyswords.effect.WildfireEffect.m_6742_(WildfireEffect.java:35) ~[simplyswords-forge-1.40-1.19.2.jar%23213!/:?] {re:classloading}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.effect.MobEffectInstance.m_19550_(MobEffectInstance.java:187) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:apoli.mixins.json:StatusEffectInstanceMixin,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.effect.MobEffectInstance.m_19552_(MobEffectInstance.java:160) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:forge:potion,re:classloading,pl:accesstransformer:B,xf:fml:forge:potion,pl:mixin:APP:apoli.mixins.json:StatusEffectInstanceMixin,pl:mixin:APP:bookshelf.common.mixins.json:effect.AccessorMobEffectInstance,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_21217_(LivingEntity.java:745) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_6075_(LivingEntity.java:418) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.Entity.m_8119_(Entity.java:417) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:apoli:apoli_prevent_suffocation,re:classloading,pl:accesstransformer:B,xf:fml:apoli:apoli_prevent_suffocation,pl:mixin:APP:oriacs.mixins.json:EntityMixin,pl:mixin:APP:apoli.mixins.json:EntityAccessor,pl:mixin:APP:apoli.mixins.json:EntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorEntity,pl:mixin:APP:supplementaries-common.mixins.json:EntityMixin,pl:mixin:APP:creatures-and-beasts.mixins.json:MixinEntity,pl:mixin:APP:origins.mixins.json:SelectionInvulnerabilityMixin,pl:mixin:APP:canary.mixins.json:alloc.deep_passengers.EntityMixin,pl:mixin:APP:canary.mixins.json:block.hopper.EntityAccessor,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.EntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_fire_check.EntityMixin,pl:mixin:APP:tombstone.mixins.json:EntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:EntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.LivingEntity.m_8119_(LivingEntity.java:2252) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:additionalentityattributes.mixins.json:common.LivingEntityMixin,pl:mixin:APP:oriacs.mixins.json:LivingEntityMixin,pl:mixin:APP:caelus.mixins.json:MixinLivingEntity,pl:mixin:APP:apoli.mixins.json:LivingEntityMixin,pl:mixin:APP:citadel.mixins.json:LivingEntityMixin,pl:mixin:APP:bookshelf.common.mixins.json:entity.AccessorLivingEntity,pl:mixin:APP:bookshelf.common.mixins.json:entity.MixinLivingEntity,pl:mixin:APP:apotheosis.mixins.json:LivingEntityMixin,pl:mixin:APP:apotheosis.mixins.json:LivingEntityInvoker,pl:mixin:APP:betterdeserttemples.mixins.json:PharaohKilledMixin,pl:mixin:APP:supplementaries-common.mixins.json:LivingEntityMixin,pl:mixin:APP:bettercombat.mixins.json:LivingEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:LivingEntityMixin,pl:mixin:APP:curios.mixins.json:MixinLivingEntity,pl:mixin:APP:origins.mixins.json:LikeWaterMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$CanBreatheInWater,pl:mixin:APP:origins_classes.mixins.json:accessor.minecraft.LivingEntityAccessor,pl:mixin:APP:crittersandcompanions.mixins.json:LivingEntityMixin,pl:mixin:APP:canary.mixins.json:alloc.enum_values.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.collisions.unpushable_cramming.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_elytra_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_hand_swing.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.fast_powder_snow_check.LivingEntityMixin,pl:mixin:APP:canary.mixins.json:entity.skip_equipment_change_check.LivingEntityMixin,pl:mixin:APP:tombstone.mixins.json:LivingEntityMixin,pl:mixin:APP:domesticationinnovation.mixins.json:LivingEntityMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.world.entity.player.Player.m_8119_(Player.java:243) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:computing_frames,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,re:classloading,pl:accesstransformer:B,xf:fml:xaeroworldmap:xaero_wm_playerentity_iswearing,pl:mixin:APP:additionalentityattributes.mixins.json:common.DigSpeedMixin,pl:mixin:APP:additionalentityattributes.mixins.json:common.PlayerEntityMixin,pl:mixin:APP:forge-mca.mixin.json:MixinPlayerEntity,pl:mixin:APP:apoli.mixins.json:PlayerEntityMixin,pl:mixin:APP:comforts.mixins.json:AccessorPlayer,pl:mixin:APP:apotheosis.mixins.json:PlayerMixin,pl:mixin:APP:supplementaries.mixins.json:PlayerProjectileMixin,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityAccessor,pl:mixin:APP:bettercombat.mixins.json:PlayerEntityMixin,pl:mixin:APP:origins.mixins.json:NoCobwebSlowdownMixin,pl:mixin:APP:origins.mixins.json:WaterBreathingMixin$UpdateAir,pl:mixin:APP:origins_classes.mixins.json:common.minecraft.PlayerMixin,pl:mixin:APP:tombstone.mixins.json:PlayerMixin,pl:mixin:APP:domesticationinnovation.mixins.json:PlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] at net.minecraft.server.level.ServerPlayer.m_9240_(ServerPlayer.java:447) ~[server-1.19.2-20220805.130853-srg.jar%23231!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:betterdeserttemples.mixins.json:ServerPlayerTickMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
22.02 22:02:44 [Server] [INFO] ... 9 more
22.02 22:02:44 [Disconnect] User Zeithelik has disconnected, reason: Internal server error
22.02 22:02:44 [Server] Server thread/[INFO] [minecraft/MinecraftServer]: Zeithelik left the game

here are the logs from my server for this issue

**Comment by n0valey** [comment]
Upon further investigation, it seems like its a conflict between a different set of mods. Sorry! If i have another issue I'll reopen this thread, thank you!
