### ISSUE TITLE
cant enchant anvil

### ISSUE THREAD

**Issue by celittle3** [Shadows-of-Fire/Apotheosis#8]
When trying to enchant anvil with unbreaking3 this happens:
09:38:17] [Server thread/ERROR] [FML]: Exception caught during firing event net.minecraftforge.event.AnvilUpdateEvent@3f02bae:
java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s()Z
at shadows.ench.anvil.ItemAnvilExt.canApplyAtEnchantingTable(ItemAnvilExt.java:20) ~[ItemAnvilExt.class:?]
at net.minecraft.enchantment.Enchantment.canApplyAtEnchantingTable(Enchantment.java:166) ~[alk.class:?]
at net.minecraft.enchantment.Enchantment.func_92089_a(Enchantment.java:137) ~[alk.class:?]
at net.minecraft.enchantment.EnchantmentDurability.func_92089_a(SourceFile:36) ~[ali.class:?]
at vazkii.quark.misc.feature.AncientTomes.onAnvilUpdate(AncientTomes.java:135) ~[AncientTomes.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_782_AncientTomes_onAnvilUpdate_AnvilUpdateEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) [EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:954) [ForgeHooks.class:?]
at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:172) [afs.class:?]
at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:472) [afs.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:1648) [pa.class:?]
at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) [lh.class:?]
at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) [lh.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) [hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) [?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) [?:1.8.0_192]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
[09:38:17] [Server thread/ERROR] [FML]: Index: 8 Listeners:
[09:38:17] [Server thread/ERROR] [FML]: 0: NORMAL
[09:38:17] [Server thread/ERROR] [FML]: 1: ASM: class thaumcraft.common.lib.events.CraftingEvents onAnvil(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 2: ASM: class crazypants.enderio.base.handler.darksteel.DarkSteelRecipeManager handleAnvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 3: ASM: net.darkhax.bookshelf.Bookshelf@5b3cf435 onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 4: ASM: class com.endertech.minecraft.forge.items.DamageableItem onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 5: ASM: shadows.ench.EnchModule@6fee34d8 anvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 6: ASM: vazkii.quark.vanity.feature.DyeItemNames@5e102cdd onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 7: ASM: vazkii.quark.misc.feature.ColorRunes@204cb4b7 onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 8: ASM: vazkii.quark.misc.feature.AncientTomes@3772a60e onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 9: ASM: class crazypants.enderio.base.loot.AnvilCapacitorRecipe handleAnvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 10: ASM: com.mcmoddev.basemetals.util.EventHandler@6057964c handleAnvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 11: ASM: class cursedflames.bountifulbaubles.recipe.AnvilRecipes onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 12: ASM: class cursedflames.bountifulbaubles.item.ItemShieldCobalt onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 13: ASM: lumien.randomthings.handler.RTEventHandler@39bfd724 anvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 14: ASM: Block{null} handleAnvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 15: ASM: com.mcmoddev.basemetals.util.EventHandler@5d170485 handleAnvilEvent(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 16: ASM: blusunrize.immersiveengineering.common.EventHandler@4c1875bc onAnvilChange(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/ERROR] [FML]: 17: LOWEST
[09:38:17] [Server thread/ERROR] [FML]: 18: ASM: ovh.corail.tombstone.handler.EventHandler@9c425f1 onAnvilUpdate(Lnet/minecraftforge/event/AnvilUpdateEvent;)V
[09:38:17] [Server thread/FATAL] [net.minecraft.server.MinecraftServer]: Error executing task
java.util.concurrent.ExecutionException: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s()Z
at java.util.concurrent.FutureTask.report(FutureTask.java:122) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.get(FutureTask.java:192) ~[?:1.8.0_192]
at net.minecraft.util.Util.func_181617_a(SourceFile:47) [h.class:?]
at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:723) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:397) [nz.class:?]
at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:668) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_192]
Caused by: java.lang.NoSuchMethodError: net.minecraft.item.ItemStack.func_77962_s()Z
at shadows.ench.anvil.ItemAnvilExt.canApplyAtEnchantingTable(ItemAnvilExt.java:20) ~[ItemAnvilExt.class:?]
at net.minecraft.enchantment.Enchantment.canApplyAtEnchantingTable(Enchantment.java:166) ~[alk.class:?]
at net.minecraft.enchantment.Enchantment.func_92089_a(Enchantment.java:137) ~[alk.class:?]
at net.minecraft.enchantment.EnchantmentDurability.func_92089_a(SourceFile:36) ~[ali.class:?]
at vazkii.quark.misc.feature.AncientTomes.onAnvilUpdate(AncientTomes.java:135) ~[AncientTomes.class:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_782_AncientTomes_onAnvilUpdate_AnvilUpdateEvent.invoke(.dynamic) ~[?:?]
at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90) ~[ASMEventHandler.class:?]
at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182) ~[EventBus.class:?]
at net.minecraftforge.common.ForgeHooks.onAnvilChange(ForgeHooks.java:954) ~[ForgeHooks.class:?]
at net.minecraft.inventory.ContainerRepair.func_82848_d(ContainerRepair.java:172) ~[afs.class:?]
at net.minecraft.inventory.ContainerRepair.func_82850_a(ContainerRepair.java:472) ~[afs.class:?]
at net.minecraft.network.NetHandlerPlayServer.func_147349_a(NetHandlerPlayServer.java:1648) ~[pa.class:?]
at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:59) ~[lh.class:?]
at net.minecraft.network.play.client.CPacketCustomPayload.func_148833_a(CPacketCustomPayload.java:11) ~[lh.class:?]
at net.minecraft.network.PacketThreadUtil$1.run(SourceFile:13) ~[hv$1.class:?]
at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511) ~[?:1.8.0_192]
at java.util.concurrent.FutureTask.run(FutureTask.java:266) ~[?:1.8.0_192]
at net.minecraft.util.Util.func_181617_a(SourceFile:46) ~[h.class:?]

**Comment by Shadows-of-Fire** [comment]
This on a dedicated server?

**Comment by celittle3** [comment]
Yes it is.
