### ISSUE TITLE
Enchantment UI doesnt open when clicked, server spits out error code

### ISSUE THREAD

**Issue by ZuckerBubi** [Shadows-of-Fire/Apotheosis#841]
[22:23:55] [Server thread/ERROR] [minecraft/PacketUtils]: Failed to handle packet net.minecraft.network.protocol.game.ServerboundUseItemOnPacket@7c05adb4, suppressing error
java.lang.NullPointerException: Cannot invoke "shadows.apotheosis.util.FloatReferenceHolder.set(float)" because "this.eterna" is null
        at shadows.apotheosis.ench.table.ApothEnchantContainer.lambda$gatherStats$3(ApothEnchantContainer.java:266) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading}
        at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at shadows.apotheosis.ench.table.ApothEnchantContainer.gatherStats(ApothEnchantContainer.java:243) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading}
        at shadows.apotheosis.ench.table.ApothEnchantContainer.lambda$slotsChanged$1(ApothEnchantContainer.java:178) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading}
        at net.minecraft.world.inventory.ContainerLevelAccess$2.m_6721_(ContainerLevelAccess.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at shadows.apotheosis.ench.table.ApothEnchantContainer.m_6199_(ApothEnchantContainer.java:175) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading}
        at net.minecraft.world.inventory.EnchantmentMenu$1.m_6596_(EnchantmentMenu.java:30) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at net.minecraft.world.SimpleContainer.m_6836_(SimpleContainer.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,re:classloading}
        at net.minecraft.world.inventory.Slot.m_5852_(Slot.java:59) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:SlotAccessor,pl:mixin:APP:allurement.mixins.json:SlotMixin,pl:mixin:A}
        at net.minecraft.world.inventory.EnchantmentMenu.handler$zha000$open(EnchantmentMenu.java:1026) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morejs-common.mixins.json:enchanting.EnchantmentMenuMixin,pl:mixin:APP:lapisreserve.mixins.json:EnchantScreen,pl:mixin:A}
        at net.minecraft.world.inventory.EnchantmentMenu.<init>(EnchantmentMenu.java:82) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:morejs-common.mixins.json:enchanting.EnchantmentMenuMixin,pl:mixin:APP:lapisreserve.mixins.json:EnchantScreen,pl:mixin:A}
        at shadows.apotheosis.ench.table.ApothEnchantContainer.<init>(ApothEnchantContainer.java:77) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading}
        at shadows.apotheosis.ench.table.ApothEnchantBlock.lambda$getMenuProvider$0(ApothEnchantBlock.java:38) ~[Apotheosis-1.19.2-6.1.5.jar%23324!/:6.1.5] {re:classloading,pl:runtimedistcleaner:A}
        at net.minecraft.world.SimpleMenuProvider.m_7208_(SimpleMenuProvider.java:25) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at net.minecraft.server.level.ServerPlayer.m_5893_(ServerPlayer.java:966) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_serverplayer_attack,xf:fml:openpartiesandclaims:xaero_pac_serverplayerclass,pl:mixin:APP:kubejs-common.mixins.json:ServerPlayerMixin,pl:mixin:APP:yungsapi.mixins.json:ServerPlayerEntityTickMixin,pl:mixin:APP:lapisreserve.mixins.json:ServerPlayerReserve,pl:mixin:APP:botania_xplat.mixins.json:ServerPlayerMixin,pl:mixin:APP:mixins.pneumaticcraft.json:accessors.ServerPlayerAccess,pl:mixin:APP:ars_nouveau.mixins.json:camera.ANServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ServerPlayerMixin,pl:mixin:APP:netherportalfix.mixins.json:ForgeServerPlayerMixin,pl:mixin:APP:tombstone.mixins.json:ServerPlayerMixin,pl:mixin:A}
        at net.minecraft.world.level.block.EnchantmentTableBlock.m_6227_(EnchantmentTableBlock.java:82) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading,pl:accesstransformer:B}
        at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60664_(BlockBehaviour.java:714) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,re:computing_frames,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:APP:kubejs-common.mixins.json:BlockStateBaseMixin,pl:mixin:APP:starlight.mixins.json:common.blockstate.BlockStateBaseMixin,pl:mixin:APP:immersiveengineering.mixins.json:coremods.AbstractBlockStateMixin,pl:mixin:APP:ferritecore.blockstatecache.mixin.json:BlockStateBaseMixin,pl:mixin:APP:valhelsia_core.mixins.json:BlockStateBaseMixin,pl:mixin:A}
        at net.minecraft.server.level.ServerPlayerGameMode.m_7179_(ServerPlayerGameMode.java:340) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,pl:mixin:A}
        at net.minecraft.server.network.ServerGamePacketListenerImpl.m_6371_(ServerGamePacketListenerImpl.java:1060) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_servergamepacketlistenerimpl_handleinteract,pl:mixin:A}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:34) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at net.minecraft.network.protocol.game.ServerboundUseItemOnPacket.m_5797_(ServerboundUseItemOnPacket.java:8) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at net.minecraft.network.protocol.PacketUtils.m_131356_(PacketUtils.java:22) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading}
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:classloading,re:mixin}
        at net.minecraft.util.thread.BlockableEventLoop.m_6367_(BlockableEventLoop.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.m_6367_(ReentrantBlockableEventLoop.java:23) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,re:mixin,re:classloading}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:763) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_6367_(MinecraftServer.java:157) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_7245_(BlockableEventLoop.java:131) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_129961_(MinecraftServer.java:746) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_7245_(MinecraftServer.java:740) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.util.thread.BlockableEventLoop.m_18701_(BlockableEventLoop.java:140) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:computing_frames,pl:accesstransformer:B,re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B}
        at net.minecraft.server.MinecraftServer.m_130012_(MinecraftServer.java:726) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:658) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[server-1.19.2-20220805.130853-srg.jar%23535!/:?] {re:mixin,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,re:classloading,pl:accesstransformer:B,xf:fml:openpartiesandclaims:xaero_pac_minecraftserverclass,pl:mixin:APP:kubejs-common.mixins.json:MinecraftServerMixin,pl:mixin:APP:kubejs-common.mixins.json:inject_resources.MinecraftServerMixin,pl:mixin:APP:balm.mixins.json:MinecraftServerMixin,pl:mixin:A}
        at java.lang.Thread.run(Thread.java:833) [?:?] {}

**Comment by Shadows-of-Fire** [comment]
Lapis reserve is incompatible with apoth, which already adds lapis-holding functionality.  Remove it
