### ISSUE TITLE
Adventure JEI plugin broken by JEI update

### ISSUE THREAD

**Issue by loldev69** [Shadows-of-Fire/Apotheosis#846]
MC version: 1.18.2

Relevant error:
> [Render thread/ERROR] [me.je.co.lo.PluginCaller/]: Caught an error from mod plugin: class shadows.apotheosis.adventure.compat.AdventureJEIPlugin apotheosis:adventure_module
java.lang.NoClassDefFoundError: mezz/jei/config/Constants
	at shadows.apotheosis.adventure.compat.ApothSmithingCategory.<init>(ApothSmithingCategory.java:37) ~[Apotheosis-1.18.2-5.7.7.jar%2353!/:5.7.7] {re:classloading}
	at shadows.apotheosis.adventure.compat.AdventureJEIPlugin.registerCategories(AdventureJEIPlugin.java:66) ~[Apotheosis-1.18.2-5.7.7.jar%2353!/:5.7.7] {re:classloading} ...

Looking at the code, it seems that the class [ApothSmithingCategory](https://github.com/Shadows-of-Fire/Apotheosis/blob/1.18/src/main/java/shadows/apotheosis/adventure/compat/ApothSmithingCategory.java) uses the value Constants.RECIPE_GUI_VANILLA from the mezz.jei.config.Constants class: however, in newer JEI versions that value has been moved to the mezz.jei.common.Constants class, hence the error.

**Comment by Shadows-of-Fire** [comment]
bleh, guess 18.2 needs a bugfix update.

**Comment by Shadows-of-Fire** [comment]
5.8.0
