### ISSUE TITLE
Rare problem regarding Natural Bosses

### ISSUE THREAD

**Issue by SiverDX** [Shadows-of-Fire/Apotheosis#901]
Happened while I was afk

Using `Apotheosis-1.19.2-6.2.0.jar`

Not sure if Adaptive Performance Tweaks is part of the problem:
https://github.com/MarkusBordihn/BOs-Adaptive-Performance-Tweaks/blob/0e501460707f21e0c502e87c2225e85399a8a769/spawn/src/main/java/de/markusbordihn/adaptiveperformancetweaksspawn/spawn/SpawnManager.java#L219

``` log
[24May2023 14:40:25.723] [Server thread/ERROR] [net.minecraftforge.eventbus.EventBus/EVENTBUS]: Exception caught during firing event: Cannot invoke "net.minecraft.network.chat.Component.m_7383_()" because the return value of "net.minecraft.world.entity.Mob.m_7770_()" is null
	Index: 10
	Listeners:
		0: HIGHEST
		1: ASM: class de.markusbordihn.adaptiveperformancetweaksspawn.spawn.SpawnManager handleLivingSpecialSpawnEvent(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$SpecialSpawn;)V
		2: ASM: com.natamus.collective.forge.events.RegisterCollectiveEvents@1980133f onMobSpawnerSpecialSpawn(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$SpecialSpawn;)V
		3: NORMAL
		4: net.minecraftforge.eventbus.EventBus$$Lambda$1677/0x000000080138d6a0@786a2153
		5: net.minecraftforge.eventbus.EventBus$$Lambda$1677/0x000000080138d6a0@4fd50d91
		6: net.minecraftforge.eventbus.EventBus$$Lambda$1677/0x000000080138d6a0@47a1f855
		7: LOW
		8: ASM: shadows.apotheosis.adventure.AdventureEvents@19937406 special(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$SpecialSpawn;)V
		9: ASM: shadows.apotheosis.adventure.boss.BossEvents@590651c6 minibosses(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$SpecialSpawn;)V
		10: ASM: shadows.apotheosis.adventure.boss.BossEvents@590651c6 naturalBosses(Lnet/minecraftforge/event/entity/living/LivingSpawnEvent$SpecialSpawn;)V
java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.m_7383_()" because the return value of "net.minecraft.world.entity.Mob.m_7770_()" is null
	at TRANSFORMER/apotheosis@6.2.0/shadows.apotheosis.adventure.boss.BossEvents.lambda$naturalBosses$0(BossEvents.java:80)
	at java.base/java.util.ArrayList.forEach(Unknown Source)
	at TRANSFORMER/apotheosis@6.2.0/shadows.apotheosis.adventure.boss.BossEvents.naturalBosses(BossEvents.java:73)
	at TRANSFORMER/apotheosis@6.2.0/shadows.apotheosis.adventure.boss.__BossEvents_naturalBosses_SpecialSpawn.invoke(.dynamic)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
	at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
	at TRANSFORMER/forge@43.2.11/net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:199)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:186)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:127)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:117)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:356)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654)
	at TRANSFORMER/minecraft@1.19.2/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244)
	at java.base/java.lang.Thread.run(Unknown Source)

[24May2023 14:40:25.792] [Server thread/ERROR] [net.minecraft.server.MinecraftServer/]: Encountered an unexpected exception
net.minecraft.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:870) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:806) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.client.server.IntegratedServer.m_5705_(IntegratedServer.java:84) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:654) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:244) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at java.lang.Thread.run(Unknown Source) [?:?]
Caused by: java.lang.NullPointerException: Cannot invoke "net.minecraft.network.chat.Component.m_7383_()" because the return value of "net.minecraft.world.entity.Mob.m_7770_()" is null
	at shadows.apotheosis.adventure.boss.BossEvents.lambda$naturalBosses$0(BossEvents.java:80) ~[Apotheosis-1.19.2-6.2.0.jar%23478!/:6.2.0]
	at java.util.ArrayList.forEach(Unknown Source) ~[?:?]
	at shadows.apotheosis.adventure.boss.BossEvents.naturalBosses(BossEvents.java:73) ~[Apotheosis-1.19.2-6.2.0.jar%23478!/:6.2.0]
	at shadows.apotheosis.adventure.boss.__BossEvents_naturalBosses_SpecialSpawn.invoke(.dynamic) ~[Apotheosis-1.19.2-6.2.0.jar%23478!/:6.2.0]
	at net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:315) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:296) ~[eventbus-6.0.3.jar%23134!/:?]
	at net.minecraftforge.event.ForgeEventFactory.doSpecialSpawn(ForgeEventFactory.java:199) ~[forge-1.19.2-43.2.11-universal.jar%23780!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47038_(NaturalSpawner.java:186) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47045_(NaturalSpawner.java:127) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.world.level.NaturalSpawner.m_47029_(NaturalSpawner.java:117) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_8490_(ServerChunkCache.java:356) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.level.ServerChunkCache.m_201698_(ServerChunkCache.java:310) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.level.ServerLevel.m_8793_(ServerLevel.java:285) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	at net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:866) ~[client-1.19.2-20220805.130853-srg.jar%23775!/:?]
	... 5 more
```

**Comment by SiverDX** [comment]
Ok I just saw the 6.2.1 version and that there was a fix about Natural Bosses
Will use that and close this
