### ISSUE TITLE
Distant Horizons Incompatibility

### ISSUE THREAD

**Issue by I2pRandom** [Shadows-of-Fire/Apotheosis#931]
I believe this belongs on the Distant Horizons gitlab issues, but I don't have an account on there. 
There is no crash tho, so no crashlog. 

`net.minecraft.ReportedException: Feature placement
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:495)
	at TRANSFORMER/lod@1.6.5a/forge.com.seibel.lod.common.wrappers.worldGeneration.step.StepFeatures.generateGroup(StepFeatures.java:73)
	at TRANSFORMER/lod@1.6.5a/forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateDirect(BatchGenerationEnvironment.java:581)
	at TRANSFORMER/lod@1.6.5a/forge.com.seibel.lod.common.wrappers.worldGeneration.BatchGenerationEnvironment.generateLodFromList(BatchGenerationEnvironment.java:452)
	at TRANSFORMER/lod@1.6.5a/forge.com.seibel.lod.common.wrappers.worldGeneration.GenerationEvent.lambda$new$0(GenerationEvent.java:75)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NullPointerException: Cannot read field "f_59788_" because "entity" is null
	at TRANSFORMER/apotheosis@5.8.0/shadows.apotheosis.util.SpawnerStats.apply(SpawnerStats.java:40)
	at TRANSFORMER/apotheosis@5.8.0/shadows.apotheosis.adventure.spawner.SpawnerItem.place(SpawnerItem.java:57)
	at TRANSFORMER/apotheosis@5.8.0/shadows.apotheosis.adventure.spawner.RogueSpawnerFeature.m_142674_(RogueSpawnerFeature.java:37)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:183)
	at java.base/java.util.stream.IntPipeline$1$1.accept(IntPipeline.java:180)
	at java.base/java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:104)
	at java.base/java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:711)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at java.base/java.util.stream.ReferencePipeline$7$1.accept(ReferencePipeline.java:276)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkGenerator.m_183372_(ChunkGenerator.java:475)
	... 9 more`

**Comment by Shadows-of-Fire** [comment]
I don't really know what the root cause is there, but the code flow is me setting a Spawner block into the world, which generates a Spawner block entity - and then retrieving it is null.  This is a pretty grave violation of contract, and nothing I can fix.

Additionally, 1.18 is out of support.
